### ISSUE TITLE
sbt project loading issue

### ISSUE THREAD

**Issue by bharath12345** [sksamuel/avro4s#105]
Am using sbt 0.13.13. When I start sbt in the cloned project folder I see this exception which does not allow the project to load - 

    Bharadwajs-MacBook-Pro:avro4s bharadwaj$ sbt
    [info] Loading global plugins from /Users/bharadwaj/.sbt/0.13/plugins
    [info] Loading project definition from /Users/bharadwaj/code/avro4s/project
    java.lang.ClassCastException: Cannot cast com.typesafe.sbt.SbtPgp$ to sbt.Plugin
       	at java.lang.Class.cast(Class.java:3369)
       	at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
       	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
       	at sbt.ModuleUtilities$$anonfun$getCheckedObjects$1.apply(ModuleUtilities.scala:23)
       	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:376)

**Comment by bharath12345** [comment]
I changed the line in plugins.sbt to this and it works now -

    addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
