### ISSUE TITLE
Can't serialise instances of a sealed hierarchy whose trait has members

### ISSUE THREAD

**Issue by Jubobs** [sksamuel/avro4s#121]
Serialisation of instances of a trait that has no members (e.g. [`Wibble`](https://github.com/sksamuel/avro4s/blob/7fdf871d34625f334fa3ad24e4fb3d211d985fdb/avro4s-core/src/test/scala/com/sksamuel/avro4s/AvroSchemaTest.scala)) works fine, but attempting to serialise instances of a trait members (e.g. `Employee` below) results in an `UnresolvedUnionException`.

(version 1.6.4)

```
scala> sealed trait Employee { def name: String }
defined trait Employee

scala> final case class RankAndFile(name: String, jobTitle: String) extends Employee
defined class RankAndFile

scala> final case class BigBoss(name: String) extends Employee
defined class BigBoss

scala> import com.sksamuel.avro4s.AvroSchema
import com.sksamuel.avro4s.AvroSchema

scala> AvroSchema[Employee]
res0: org.apache.avro.Schema = {"type":"record","name":"Employee","namespace":"$iw","fields":[{"name":"jobTitle","type":["null","string"]},{"name":"name","type":["string"]}]}

scala> import java.io.File
import java.io.File

scala> import com.sksamuel.avro4s.AvroOutputStream
import com.sksamuel.avro4s.AvroOutputStream

scala> val joe = RankAndFile("Joe", "grunt")
joe: RankAndFile = RankAndFile(Joe,grunt)

scala> val bob = BigBoss("Bob")
bob: BigBoss = BigBoss(Bob)

scala> val os = AvroOutputStream.data[Employee](new File("employees.avro"))
os: com.sksamuel.avro4s.AvroDataOutputStream[Employee] = AvroDataOutputStream(java.nio.channels.Channels$1@8950cb2)

scala> os.write(Seq(joe, bob))
org.apache.avro.file.DataFileWriter$AppendWriteException: org.apache.avro.UnresolvedUnionException: Not in union ["string"]: null
  at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:308)
  at com.sksamuel.avro4s.AvroDataOutputStream$$anonfun$2.apply(AvroOutputStream.scala:54)
  at com.sksamuel.avro4s.AvroDataOutputStream$$anonfun$2.apply(AvroOutputStream.scala:52)
  at com.sksamuel.avro4s.AvroDataOutputStream.write(AvroOutputStream.scala:64)
  at com.sksamuel.avro4s.AvroOutputStream$$anonfun$write$1.apply(AvroOutputStream.scala:16)
  at com.sksamuel.avro4s.AvroOutputStream$$anonfun$write$1.apply(AvroOutputStream.scala:16)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at com.sksamuel.avro4s.AvroOutputStream$class.write(AvroOutputStream.scala:16)
  at com.sksamuel.avro4s.AvroDataOutputStream.write(AvroOutputStream.scala:38)
  ... 42 elided
Caused by: org.apache.avro.UnresolvedUnionException: Not in union ["string"]: null
  at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:709)
  at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:192)
  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:110)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
  at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:153)
  at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:60)
  at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:302)
  ... 50 more
```

**Comment by sksamuel** [comment]
Working in 1.8.2
