### ISSUE TITLE
Can't deserialize Either or Coproduct unions

### ISSUE THREAD

**Issue by ryanworsley** [sksamuel/avro4s#129]
Hi,

I have code like this;

```
object Main extends App {
  val schema = AvroSchema[Fact]
  val format = RecordFormat[Fact]
  val record1 = format.to(Fact("1", "name", Coproduct[Value]("ryan")))
  val record2 = format.to(Fact("1", "age", Coproduct[Value](35)))

  val fact1 = format.from(record1)
  val fact2 = format.from(record2)

  println(schema)
  println(record1)
  println(record2)
  println(fact1)
  println(fact2)
}

case class Fact(
  entity: String,
  attribute: String,
  value: Value)

```
It fails on the attempt to deserialize `fact1` with the following error;

```
Exception in thread "main" java.lang.RuntimeException: Value ryan of type class java.lang.String is not compatible with [value]
	at scala.sys.package$.error(package.scala:27)
	at com.sksamuel.avro4s.FromValue$$anon$12.apply(FromRecord.scala:203)
	at com.sksamuel.avro4s.FromValue$$anon$12.apply(FromRecord.scala:202)
	at com.sksamuel.avro4s.FromValue$$anon$13.$anonfun$apply$18(FromRecord.scala:215)
	at com.sksamuel.avro4s.FromValue$$anon$13$$Lambda$235/1217312754.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:121)
	at com.sksamuel.avro4s.FromValue$$anon$13.apply(FromRecord.scala:215)
	at com.sksamuel.avro4s.FromValue$$anon$13.apply(FromRecord.scala:212)
	at com.sksamuel.avro4s.FromValue$$anon$13.$anonfun$apply$18(FromRecord.scala:215)
	at com.sksamuel.avro4s.FromValue$$anon$13$$Lambda$235/1217312754.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:121)
	at com.sksamuel.avro4s.FromValue$$anon$13.apply(FromRecord.scala:215)
	at com.sksamuel.avro4s.FromValue$$anon$13.apply(FromRecord.scala:212)
	at Main$$anon$2.apply(Main.scala:14)
	at Main$$anon$2.apply(Main.scala:14)
	at com.sksamuel.avro4s.RecordFormat$$anon$1.from(RecordFormat.scala:12)
	at Main$.delayedEndpoint$Main$1(Main.scala:18)
	at Main$delayedInit$body.apply(Main.scala:12)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.App$$Lambda$5/1221555852.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Main$.main(Main.scala:12)
	at Main.main(Main.scala)
```

Have I misunderstood the intended syntax or is this a bug?

**Comment by ryanworsley** [comment]
I forgot to add this is Scala 2.12.1 and avro4s 1.6.4 - the bug occurs using the Either type also.

**Comment by ryanworsley** [comment]
Any thoughts on this?

**Comment by ryanworsley** [comment]
Paging @sksamuel!
