### ISSUE TITLE
Problem with serializzation of class that use Generic Serialization/Deserialization methods

### ISSUE THREAD

**Issue by francescofrontera** [sksamuel/avro4s#139]
Hi,  I'm encountering an issue when I try to create a custom class for Serialized Avro in  [Flink-Kafka-Connector](https://ci.apache.org/projects/flink/flink-docs-release-1.3/dev/connectors/kafka.html).

I'll try to attempt to explain the context briefly:

```
class FlinkSerDes[IN: SchemaFor: FromRecord: ToRecord: TypeInformation]
    extends DeserializationSchema[IN]
    with SerializationSchema[IN] {

  override def isEndOfStream(nextElement: IN): Boolean =
    false

  override def deserialize(message: Array[Byte]): IN = {
    lazy val inputStream = AvroInputStream.json[IN](message)
    val result           = inputStream.singleEntity
    inputStream.close()
    result.getOrElse(throw new IOException("NOT SER"))
  }

  override def serialize(element: IN): Array[Byte] = {
    val byteArrayOutputStream = new ByteArrayOutputStream()
    lazy val output           = AvroOutputStream.json[IN](byteArrayOutputStream)
    output.write(element)
    output.close()
    byteArrayOutputStream.toByteArray
  }

  override def getProducedType: TypeInformation[IN] =
    createTypeInformation[IN]

}
```
This rappresents the custom generic serializer that implements  `DeserializationSchema` and `SerializationSchema` from package `org.apache.flink.streaming.util.serialization`, whene i try to execute a : 

```
object SourceExample {

  private final val serDesSchema = new FlinkSerDes[FullName]()

  final val KakfaServer   = "localhost:9092"
  final val ZookeeperHost = "localhost:2181"

  val props = new Properties()
  props.setProperty("bootstrap.servers", KakfaServer)
  props.setProperty("zookeeper.connect", ZookeeperHost)

  def main(args: Array[String]): Unit = {
     val env = StreamExecutionEnvironment.getExecutionEnvironment

    val consumer = new FlinkKafkaConsumer010("top", serDesSchema, props)
    consumer.setStartFromEarliest()
    env.addSource(consumer)

    env.execute("SIMP JOB")
  }

}
```

i do get the following exception:
```
[error] (run-main-7) org.apache.flink.api.common.InvalidProgramException: Task not serializable
org.apache.flink.api.common.InvalidProgramException: Task not serializable
	at org.apache.flink.api.scala.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:172)
	at org.apache.flink.api.scala.ClosureCleaner$.clean(ClosureCleaner.scala:164)
	at org.apache.flink.streaming.api.scala.StreamExecutionEnvironment.scalaClean(StreamExecutionEnvironment.scala:670)
	at org.apache.flink.streaming.api.scala.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.scala:600)
	at my.package.with.kafka.SourceExample$.main(SourceExample.scala:26)
	at my.package.with.SourceExample.main(SourceExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.io.NotSerializableException: my.package.with.SourceExample$$anon$7
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:315)
	at org.apache.flink.api.scala.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:170)
	at org.apache.flink.api.scala.ClosureCleaner$.clean(ClosureCleaner.scala:164)
	at org.apache.flink.streaming.api.scala.StreamExecutionEnvironment.scalaClean(StreamExecutionEnvironment.scala:670)
	at org.apache.flink.streaming.api.scala.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.scala:600)
	at my.package.with.SourceExample$.main(SourceExample.scala:26)
	at my.package.with.SourceExample.main(SourceExample.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

i tried to testing if  `FlinkSerDes` is serializable (FullName case class has been generated with [sbt-avrohugger](https://github.com/julianpeeters/sbt-avrohugger)) : 

```
val g = new FlinkSerDes[FullName]
new ObjectOutputStream(new ByteArrayOutputStream())
        .writeObject(g)
```

i do get the following exception:
```
java.io.NotSerializableException: my.package.with.AvroSerDeSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anon$5
[info]   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
[info]   at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
[info]   at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
[info]   at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
[info]   at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
[info]   at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
[info]   at my.package.with.AvroSerDeSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(AvroSerDeSpec.scala:39)
[info]   at my.package.with.AvroSerDeSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AvroSerDeSpec.scala:35)
[info]   at my.package.with.AvroSerDeSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AvroSerDeSpec.scala:35)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```
any idea? Thanks.

**Comment by sksamuel** [comment]
This is an issue where Flink needs to serialize your function to send it over to the cluster. I don't know much about Flink, but I imagine the issue is the same that faces Spark users. The trick is to find out what is being serialized and instead of the closure cleaner grabbing a reference to it, create the instance inside the function. It's not clear to me from your code where that would happen, but maybe that can help.

**Comment by wzorgdrager** [comment]
You probably have to annotate the `serDesSchema` with `@transient` and make it `lazy` as well (so `@transientprivate final lazy val serDesSchema = new FlinkSerDes[FullName]()`) . That will instantiate the deserialization schema on the worker. See: https://flink.apache.org/faq.html#i-have-a-notserializableexception

**Comment by francescofrontera** [comment]
Thanks to the reply @sksamuel @wzorgdrager. 
@wzorgdrager your solution solved the problem!
