### ISSUE TITLE
BigDecimalToValue needs setScale

### ISSUE THREAD

**Issue by ericaovo** [sksamuel/avro4s#141]
I found a problem when using a BigDecimal that has a 0 as last digit in the scale. 

Running the following test on `1.8.0`:
```
"BigDecimalAvro" should {
    "convert a BigDecimal into ByteBuffer (and back) with the correct scale" in {
      val n = BigDecimal(5.00)
      BigDecimalFromValue.apply(BigDecimalToValue.apply(n)) shouldBe n
    }
  }
```

it fails with the following problem:
```
should convert a BigDecimal into ByteBuffer (and back) with the correct scale *** FAILED *** (243 milliseconds)
[info]   org.apache.avro.AvroTypeException: Cannot encode decimal with scale 1 as scale 2
[info]   at org.apache.avro.Conversions$DecimalConversion.toBytes(Conversions.java:86)
[info]   at com.sksamuel.avro4s.ToValue$$anon$3.apply(ToRecord.scala:83)
[info]   at com.sksamuel.avro4s.ToValue$$anon$3.apply(ToRecord.scala:81)
```

By default, `BigDecimal` has a `scale` of 1, even if in this case I use a number with 2 digits `scale`.
Looking at the code (`ToRecord.scala` line 83) I found that this problem can be avoided setting the `scale` on the value in the `apply` method, as follows:
```
implicit def BigDecimalToValue(implicit sp: ScaleAndPrecision = defaultScaleAndPrecision): ToValue[BigDecimal] = {
    val decimalConversion = new Conversions.DecimalConversion
    val decimalType = LogicalTypes.decimal(sp.precision, sp.scale)
    new ToValue[BigDecimal] {
      override def apply(value: BigDecimal): ByteBuffer = {
        decimalConversion.toBytes(value.setScale(sp.scale).bigDecimal, null, decimalType)
      }
    }
  }
```
I know it would be enough to set the scale on the `BigDecimal` value, but, if we were reading this value from (e.g.) a db (my case), this approach would be easier.

Happy to open a PR in case this fix is accepted.

**Comment by sksamuel** [comment]
Yes please.
