### ISSUE TITLE
Avro4s invalid output

### ISSUE THREAD

**Issue by mamdouhweb** [sksamuel/avro4s#162]
First of all, happy holidays and happy early new year!

I'm generating an avro data file using the following code:
```scala
def serializeAvroMessage(message: Seq[T])(implicit schema: SchemaFor[T], toRecord: ToRecord[T]): Array[Byte] = {
    val binarySerializer = new ByteArrayOutputStream()
    val output = AvroOutputStream.data[T](binarySerializer)
    output.write(message)
    output.close()
    binarySerializer.toByteArray
  }
```

and when I run `avro-tools` on the output file I get the following exception. 
```java
java.lang.IllegalArgumentException
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:334)
	at org.apache.avro.io.BinaryDecoder.readBytes(BinaryDecoder.java:288)
	at org.apache.avro.file.DataFileStream.initialize(DataFileStream.java:112)
	at org.apache.avro.file.DataFileReader.<init>(DataFileReader.java:97)
	at org.apache.avro.file.DataFileReader.openReader(DataFileReader.java:59)
	at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1.apply(DefaultSource.scala:182)
	at com.databricks.spark.avro.DefaultSource$$anonfun$buildReader$1.apply(DefaultSource.scala:160)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:136)
...
```

I went through all debugging options and all possible scenarios to no results. Your help would be extremely appreciated.

avro tools command:

```bash
avro-tools getmeta tempfile.avro
```

avro file output:

```
Objavro.schema�{"type":"record","name":"r1","namespace":"avroPayload","fields":[{"name":"f1","type":"string"},{"name":"secret","type":"string"},{"name":"f2","type":"string"},{"name":"f3","type":"string"}]}avro.codecnull��+܀���Ι吻��Namely12345678A*accountId6.x.comaccountId6ADP123456789AA$accountId6.y.comaccountId6��+܀���Ι吻�
```

**Comment by mamdouhweb** [comment]
The issue is not in avro4s itself, but the writer I was using. Closing the issue
