### ISSUE TITLE
cannot serialize optional enumeratum enums

### ISSUE THREAD

**Issue by quiquedeveloper** [sksamuel/avro4s#185]
hello! i have the same problem described in https://github.com/sksamuel/avro4s/issues/175 :(
even if im using the last version (1.8.3) i get NullPointerException when having an optional enum.

scenario:

having the following enum:
```
package de.enrique

import enumeratum.{EnumEntry, PlayEnum}

sealed trait PersonType extends EnumEntry
object PersonType extends PlayEnum[PersonType] {
  val values = findValues

  case object Rich extends PersonType
  case object Poor extends PersonType
}
```

and the following case class that i want to deserialize:
```
package de.enrique

import com.sksamuel.avro4s.{FromRecord, SchemaFor, ToRecord}
import realestate.reporting.events.ReportEvent

case class Person(name: String, personType: Option[PersonType])
object Person {
  implicit val schema: SchemaFor[ReportEvent] = SchemaFor[ReportEvent]
  implicit val toRecord: ToRecord[ReportEvent] = ToRecord[ReportEvent]
  implicit val fromRecord: FromRecord[ReportEvent] = FromRecord[ReportEvent]
}
```

the following code fails:

```
import java.io.ByteArrayOutputStream

import com.sksamuel.avro4s.AvroOutputStream
import de.enrique.{Person, PersonType}

object EnriqueTest extends App {
  def toBinaryBytes(person: Person): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val output = AvroOutputStream.binary[Person](baos)
    output.write(person)
    output.close()
    baos.toByteArray
  }

  toBinaryBytes(Person("enrique", Some(PersonType.Poor)))
}
```

and the stacktrace is:

```
Exception in thread "main" java.lang.NullPointerException: null of union in field personType of de.enrique.Person
	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:145)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:139)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:62)
	at com.sksamuel.avro4s.AvroBinaryOutputStream.write(AvroOutputStream.scala:32)
	at EnriqueTest$.toBinaryBytes(EnriqueTest.scala:10)
	at EnriqueTest$.delayedEndpoint$EnriqueTest$1(EnriqueTest.scala:15)
	at EnriqueTest$delayedInit$body.apply(EnriqueTest.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at EnriqueTest$.main(EnriqueTest.scala:6)
	at EnriqueTest.main(EnriqueTest.scala)
Caused by: java.lang.NullPointerException
	at org.apache.avro.generic.GenericData.getSchemaName(GenericData.java:751)
	at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:737)
	at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:205)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:123)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:75)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:166)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:156)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:118)
	... 15 more
```

it works in the case im passing _None_ in the optional field instead of _Some_

**Comment by sksamuel** [comment]
I don't plan to support enumeratum - just scala enums and java enums.
