### ISSUE TITLE
@transient annotation to avoid serializing some fields

### ISSUE THREAD

**Issue by SpyQuel** [sksamuel/avro4s#192]
Is it possible to annotate some fields of a case class to be ignored by serialization? (e.g. @transient)
Obviously all fields with such annotation should be Options in order to not have problems deserializing them (or some other technique that lets you create an instance without them).

If not, is there a way to achieve such result in the state-of-the-art release?

**Comment by s4nk** [comment]
This would be quite useful, @SpyQuel have you found any solution for that?

**Comment by sksamuel** [comment]
This is working in 2.0.0-M3 if you want to give it a go and report back.

**Comment by sksamuel** [comment]
2.0.0 is now released, so closing this ticket.

**Comment by jquadrino** [comment]
would the opposite be possible? Deserializing into a case class but ignoring some fields in the avro record.

**Comment by sksamuel** [comment]
It might just do that be default as the looks are driven from the case class definitions @jquadrino

**Comment by jquadrino** [comment]
I just tried this but I got the following error, it seems to be looking for a indexedrecord type.
```
Exception in thread "application_id-e3731f54-9d93-4ec4-8c28-91b156169be3-StreamThread-1" java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:264)
	at com.sksamuel.avro4s.Decoder$$anon$11.decode(Decoder.scala:348)
	at com.sksamuel.avro4s.Decoder$$anon$4.decode(Decoder.scala:210)
	at com.sksamuel.avro4s.Decoder$$anon$4.decode(Decoder.scala:198)
	at com.sksamuel.avro4s.DecoderHelper$.$anonfun$tryDecode$1(DecoderHelper.scala:11)
	at scala.util.Try$.apply(Try.scala:209)
	at com.sksamuel.avro4s.DecoderHelper$.tryDecode(DecoderHelper.scala:11)
	at com.sksamuel.avro4s.Decoder$$anon$11.$anonfun$decode$12(Decoder.scala:389)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.sksamuel.avro4s.Decoder$$anon$11.decode(Decoder.scala:349)
	at com.sksamuel.avro4s.Decoder$$anon$4.decode(Decoder.scala:210)
	at com.sksamuel.avro4s.Decoder$$anon$4.decode(Decoder.scala:198)
	at com.sksamuel.avro4s.DecoderHelper$.$anonfun$tryDecode$1(DecoderHelper.scala:11)
	at scala.util.Try$.apply(Try.scala:209)
	at com.sksamuel.avro4s.DecoderHelper$.tryDecode(DecoderHelper.scala:11)
	at com.sksamuel.avro4s.Decoder$$anon$11.$anonfun$decode$12(Decoder.scala:389)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.sksamuel.avro4s.Decoder$$anon$11.decode(Decoder.scala:349)
	at com.sksamuel.avro4s.Decoder$$anon$4.decode(Decoder.scala:210)
	at com.sksamuel.avro4s.Decoder$$anon$4.decode(Decoder.scala:198)
	at com.sksamuel.avro4s.FromRecord$$anon$1.from(FromRecord.scala:16)
	at com.sksamuel.avro4s.RecordFormat$$anon$1.from(RecordFormat.scala:22)
	at com.shutterstock.AssetPageView$.$anonfun$stream$1(asset_page_view.scala:32)
	at org.apache.kafka.streams.scala.FunctionsCompatConversions$ValueMapperFromFunction$$anon$6.apply(FunctionsCompatConversions.scala:66)
	at org.apache.kafka.streams.kstream.internals.AbstractStream.lambda$withKey$1(AbstractStream.java:103)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:40)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:117)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:183)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:162)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:122)
	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:87)
	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:364)
	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:199)
	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:420)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:890)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:805)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:774)
```

**Comment by sksamuel** [comment]
Do you have sample code?
