### ISSUE TITLE
Alias avro schema feature problem

### ISSUE THREAD

**Issue by thiaguten** [sksamuel/avro4s#202]
I'm trying to use the alias feature from Avro to support schema evolution.

According to this [post](http://blog.cloudera.com/blog/2011/05/three-reasons-why-apache-avro-data-serialization-is-a-good-choice-for-openrtb/), in the topic of schema evolution, Avro supports aliases to retrieve values ​​from renamed fields.

I'm trying to do this using this avro4s library as below:

```scala
package br.com.thiaguten.scala

import java.io.ByteArrayOutputStream

import com.sksamuel.avro4s.{AvroAlias, AvroInputStream, AvroOutputStream, AvroSchema}

object Test extends App {

  // support schema evolution

  case class Version1(string: String)

  case class Version2(@AvroAlias("string") renamed: String, `new`: String = "default")

  println(AvroSchema[Version1].toString(true))
  println(AvroSchema[Version2].toString(true))

  val v1 = Version1("hello")
  val baos = new ByteArrayOutputStream()
  val output = AvroOutputStream.binary[Version1](baos)
  output.write(v1)
  output.close()

  val is = AvroInputStream.binary[Version2](baos.toByteArray, AvroSchema[Version1])
  val v2 = is.iterator.toList.head
  is.close()

  assert(v2.renamed == v1.string)
  assert(v2.`new` == "default")

}
```

But the following Exception is occurring:

```
Exception in thread "main" org.apache.avro.AvroTypeException: Found br.com.thiaguten.scala.Version1, expecting br.com.thiaguten.scala.Version2, missing required field renamed
	at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:292)
	at org.apache.avro.io.parsing.Parser.advance(Parser.java:88)
	at org.apache.avro.io.ResolvingDecoder.readFieldOrder(ResolvingDecoder.java:130)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:215)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145)
	at com.sksamuel.avro4s.AvroBinaryInputStream.$anonfun$_iter$1(AvroInputStream.scala:30)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:170)
	at scala.collection.Iterator$$anon$15.hasNext(Iterator.scala:652)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$1.hasNext(AvroInputStream.scala:37)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$1.foreach(AvroInputStream.scala:36)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:186)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:44)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$1.to(AvroInputStream.scala:36)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:294)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:294)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$1.toList(AvroInputStream.scala:36)
	at br.com.thiaguten.scala.Test$.delayedEndpoint$br$com$thiaguten$scala$Test$1(Test.scala:22)
	at br.com.thiaguten.scala.Test$delayedInit$body.apply(Test.scala:7)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at br.com.thiaguten.scala.Test$.main(Test.scala:7)
	at br.com.thiaguten.scala.Test.main(Test.scala)
```

I would like to know what I am doing wrong and how to do it correctly.

Thank you

**Comment by s4nk** [comment]
looks like there is already an issue open for that: https://github.com/sksamuel/avro4s/issues/177

**Comment by sksamuel** [comment]
I don't think this is an avro4s issue.
The schema is being generated properly with the alias fields.
I cannot get this to work on the regular Java API, without any scala code at all.
Can anyone else get it to work in Java ?

**Comment by bobbyrauchenberg** [comment]
@thiaguten @sksamuel 

This can be made to work in both Avro4s and java by annotating all the fields. 

I'll add a PR updating the test and also giving a full java version which sort of makes it clearer what the issue is

**Comment by bobbyrauchenberg** [comment]
This PR has a fix for the related test

https://github.com/sksamuel/avro4s/pull/376

**Comment by sksamuel** [comment]
Fix is merged. Thanks @bobbyrauchenberg

**Comment by thiaguten** [comment]
Thanks! @bobbyrauchenberg
