### ISSUE TITLE
shapless tagged type is not working

### ISSUE THREAD

**Issue by muradm** [sksamuel/avro4s#206]
Consider tagged type:
```
  type EventName = String @@ EventName.Tag
  object EventName { trait Tag; def apply(n: String): EventName = shapeless.tag[EventName.Tag][String](n) }
```
Then `AvroSchema[EventName]` and this `SchemaFor[EventName]` fails with:
```
Error:(51, 43) exception during macro expansion: 
scala.ScalaReflectionException: <none> is not a term
	at scala.reflect.api.Symbols$SymbolApi.asTerm(Symbols.scala:199)
	at scala.reflect.api.Symbols$SymbolApi.asTerm$(Symbols.scala:199)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asTerm(Symbols.scala:94)
	at com.sksamuel.avro4s.TypeHelper.primaryConstructor(TypeHelper.scala:13)
	at com.sksamuel.avro4s.TypeHelper.fieldsOf(TypeHelper.scala:19)
	at com.sksamuel.avro4s.SchemaFor$.applyImpl(SchemaFor.scala:351)
  implicit val eventNameSchema = SchemaFor[EventName]
Error:(53, 21) Could not find implicit SchemaFor[test.EventName]
  println(AvroSchema[EventName])
Error:(53, 21) not enough arguments for method apply: (implicit schemaFor: com.sksamuel.avro4s.SchemaFor[net.encom.rwb.cqrs.api.EventName])org.apache.avro.Schema in object AvroSchema.
Unspecified value parameter schemaFor.
  println(AvroSchema[EventName])
```
Although implicit conversion is provided:
```
  object Avro4sHelpers {
    implicit object EventNameToSchema extends ToSchema[EventName] {
      override val schema: Schema = Schema.create(Schema.Type.STRING)
    }

    implicit object EventNameToValue extends ToValue[EventName] {
      override def apply(value: EventName): String = value
    }

    implicit object EventNameFromValue extends FromValue[EventName] {
      override def apply(value: Any, field: Field): EventName = EventName(value.toString)
    }
  }

  import Avro4sHelpers._
```
Still not working.

**Comment by muradm** [comment]
This works without implicit `ToSchema` & friends.
```
  final case class EventName(value: String) extends AnyVal
  implicit def EventNameString(en: EventName): String = en.value
```
But it is not solution.

**Comment by sksamuel** [comment]
I don't plan to add support for shapeless tagged types.
