### ISSUE TITLE
Broken typeclass derivation upgrading from 1.9.0 to 2.0.1

### ISSUE THREAD

**Issue by Astrac** [sksamuel/avro4s#235]
I am using avro4s to auto-generate kafka serdes with a function that looked like this in 1.9.0:

```scala
object AutoSerde {
  def apply[A](
      implicit fromRecord: FromRecord[A],
      toRecord: ToRecord[A],
      schemaFor: SchemaFor[A]
  ): Serde[A] = {

    val schema = schemaFor()
    val datumReader = new GenericDatumReader[GenericRecord](schema)
    val datumWriter = new GenericDatumWriter[GenericRecord](schema)
    ... // Uses datumReader and datumWriter to implement the serde
  }
}
```

Upgrading to 2.0.1 it looks like this:

```scala
object AutoSerde {
  def apply[A <: Product](
      implicit schemaFor: SchemaFor[A],
      encoder: Encoder[A],
      decoder: Decoder[A]
  ): Serde[A] = {

    val format = RecordFormat[A]
    val schema = schemaFor.schema
    val datumReader = new GenericDatumReader[GenericRecord](schema)
    val datumWriter = new GenericDatumWriter[GenericRecord](schema)
    ... // Uses datumReader and datumWriter to implement the serde
  }
}
```

I also have a property-based test that serialises and deserialises this ADT usign a `Serde` generated this way:

```scala
  object AutoSerdeSpecModel {
    case class Label(value: String) extends AnyVal
    case class Value[A](label: Label, value: A)

    sealed trait OneOrTwo[A]
    case class One[A](value: Value[A]) extends OneOrTwo[A]
    case class Two[A](first: Value[A], second: Value[A]) extends OneOrTwo[A]

    case class OneOrTwoWrapper[A](t: OneOrTwo[A])
  }

  class MySpec extends ... {
    def checkOne[T: Arbitrary](serde: Serde[T])(beforeSerde: T): Boolean = {
      val afterSerde = serde
        .deserializer()
        .deserialize(topic, serde.serializer().serialize(topic, beforeSerde))

      afterSerde == beforeSerde
    }

    "Derive a working serde for a generic coproduct type" in {
      Checkers.check(property(AutoSerde[OneOrTwoWrapper[Int]]))
    }
  }
```

In the 1.9.0 version everything works fine, in the 2.0.1 it fails with the error:

```
 Cannot find subschema for class my.package.AutoSerdeSpecModel.One
```

or:

```
 Cannot find subschema for class my.package.AutoSerdeSpecModel.Two
```

Any idea of the reason why this happens? Is it caused by a bug or am I using the wrong typeclasses?

**Comment by sksamuel** [comment]
In 2.0 it passes the schema around when encoding and decoding. It's trying and failing to find the correct subschema in the union. Likely to be a bug in how it builds the package name for traits inside objects.

**Comment by Astrac** [comment]
I see, thanks for the reply, I will downgrade to 1.9.0 for now; just in case this is useful for diagnosing the bug the error happens also if I don't wrap my ADT in an `object` and this is the relevant part of the stack trace:

```
Cannot find subschema for class com.iov42.serialisation.kafka.One
        at scala.sys.package$.error(package.scala:27)
        at com.sksamuel.avro4s.SchemaHelper$.$anonfun$extractTraitSubschema$3(SchemaHelper.scala:14)
        at scala.Option.getOrElse(Option.scala:121)
        at com.sksamuel.avro4s.SchemaHelper$.extractTraitSubschema(SchemaHelper.scala:14)
        at com.sksamuel.avro4s.Encoder$.encodeField(Encoder.scala:361)
        at my.package.AutoSerdeSpec$$anon$16$$anon$17.encode(AutoSerdeSpec.scala:41)
        at my.package.AutoSerdeSpec$$anon$16$$anon$17.encode(AutoSerdeSpec.scala:41)
        at com.sksamuel.avro4s.CoproductEncoders$$anon$3.encode(CoproductEncoders.scala:32)
        at com.sksamuel.avro4s.CoproductEncoders$$anon$3.encode(CoproductEncoders.scala:29)
        at com.sksamuel.avro4s.CoproductEncoders$$anon$1.encode(CoproductEncoders.scala:12)
        at com.sksamuel.avro4s.Encoder$.encodeField(Encoder.scala:366)
        at my.package.AutoSerdeSpec$$anon$16.encode(AutoSerdeSpec.scala:41)
        at my.package.AutoSerdeSpec$$anon$16.encode(AutoSerdeSpec.scala:41)
        at com.sksamuel.avro4s.ToRecord$$anon$1.to(ToRecord.scala:25)
        at com.sksamuel.avro4s.RecordFormat$$anon$1.to(RecordFormat.scala:23)
```

I'll see if I can find the cause myself when I have some time 👍

**Comment by sksamuel** [comment]
Is that stack trace from top level trait and classes?

**Comment by Astrac** [comment]
yes, I only replaced the company's namespace with `my.package` but the ADT I shared in the first message is defined at the package level in that stack trace, not inside other objects or classes.

**Comment by sksamuel** [comment]
Can you give me a full example, I don't have this Serde class - happy to add Kafka to the test path - or just a stand alone example of this schema failing. And then I will fix it.

**Comment by Astrac** [comment]
Sure, this is a self-contained example that results in the same error:

```scala
import com.sksamuel.avro4s.{Decoder, Encoder, RecordFormat, SchemaFor}
import java.io.ByteArrayOutputStream
import org.apache.avro.generic.{GenericDatumReader, GenericDatumWriter, GenericRecord}
import org.apache.avro.io.{DecoderFactory, EncoderFactory}

case class Label(value: String) extends AnyVal
case class Value[A](label: Label, value: A)

sealed trait OneOrTwo[A]
case class One[A](value: Value[A]) extends OneOrTwo[A]
case class Two[A](first: Value[A], second: Value[A]) extends OneOrTwo[A]

case class OneOrTwoWrapper[A](t: OneOrTwo[A])

object Bug {

  def apply[A <: Product](a: A)(
      implicit schemaFor: SchemaFor[A],
      encoder: Encoder[A],
      decoder: Decoder[A]
  ): Unit = {

    val format = RecordFormat[A]
    val schema = schemaFor.schema
    val datumReader = new GenericDatumReader[GenericRecord](schema)
    val datumWriter = new GenericDatumWriter[GenericRecord](schema)

    val stream = new ByteArrayOutputStream()
    val bEncoder = EncoderFactory.get().binaryEncoder(stream, null)

    datumWriter.write(format.to(a), bEncoder)
    bEncoder.flush()

    val bytes = stream.toByteArray()
    val bDecoder = DecoderFactory.get().binaryDecoder(bytes, null)
    val record = datumReader.read(null, bDecoder)
    println(format.from(record))
  }

}
```

Running it:

```
scala> val o = OneOrTwoWrapper(One(Value(Label("lbl"), "foo")))
o: com.iov42.serialisation.kafka.avro4sbug.OneOrTwoWrapper[String] = OneOrTwoWrapper(One(Value(Label(lbl),foo)))

scala> Bug(o)
java.lang.RuntimeException: Cannot find subschema for class com.iov42.serialisation.kafka.avro4sbug.One
  at scala.sys.package$.error(package.scala:27)
  at com.sksamuel.avro4s.SchemaHelper$.$anonfun$extractTraitSubschema$3(SchemaHelper.scala:14)
  at scala.Option.getOrElse(Option.scala:121)
  at com.sksamuel.avro4s.SchemaHelper$.extractTraitSubschema(SchemaHelper.scala:14)
  at com.sksamuel.avro4s.Encoder$.encodeField(Encoder.scala:361)
  at $anon$10$$anon$11.encode(<console>:16)
  at $anon$10$$anon$11.encode(<console>:16)
  at com.sksamuel.avro4s.CoproductEncoders$$anon$3.encode(CoproductEncoders.scala:32)
  at com.sksamuel.avro4s.CoproductEncoders$$anon$3.encode(CoproductEncoders.scala:29)
  at com.sksamuel.avro4s.CoproductEncoders$$anon$1.encode(CoproductEncoders.scala:12)
  at com.sksamuel.avro4s.Encoder$.encodeField(Encoder.scala:366)
  at $anon$10.encode(<console>:16)
  at $anon$10.encode(<console>:16)
  at com.sksamuel.avro4s.ToRecord$$anon$1.to(ToRecord.scala:25)
  at com.sksamuel.avro4s.RecordFormat$$anon$1.to(RecordFormat.scala:23)
  at com.iov42.serialisation.kafka.avro4sbug.Bug$.apply(Avro4sBug.scala:33)
  ... 36 elided
```

**Comment by sksamuel** [comment]
This is now fixed in master.
See test here:
https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/test/scala/com/sksamuel/avro4s/github/GithubIssue235.scala

I'll release 2.0.2 once @alexjg has finished his changes.

**Comment by Astrac** [comment]
Thanks a lot for the fast resolution :)

**Comment by sksamuel** [comment]
Please try 2.0.2

**Comment by tiboun** [comment]
Hi, I would like to know if it's mandatory to add a wrapper instead of using the ADT directly? It seems so because the trait is not a product, so RecordFormat is not able to be instantiated.

**Comment by sksamuel** [comment]
In 2.0.3 I've dropped the requirement for RecordFormat's to use Product so it should work with traits now.

**Comment by tiboun** [comment]
Thanks for this release!

In this commit on master https://github.com/sksamuel/avro4s/commit/c5e2c77664a440e1e11327e197034eef66f6d651#diff-d0220eee47658ffbede3d26041cf396d scala 2.11 has been dropped. Since then, 2.0.3 is not available for 2.11, is it by purpose? 

We are still using 2.11, is compatiblity with 2.11 dropped officially by Avro4s ?

**Comment by sksamuel** [comment]
If 2.11 works from master I'll do a release for it.

But if not, I won't spend time fixing it. Scala 2.12 has been out for 2 years and Scala 2.13 is about to come out, so that's the focus.

**Comment by tiboun** [comment]
Hi, I would like to know if you manage to build with 2.11 or if it fails or you didn't have time to release it. Thanks
