### ISSUE TITLE
Avro Schema for a sealed trait in a subobject

### ISSUE THREAD

**Issue by RomanBrodetski** [sksamuel/avro4s#281]
I'm trying to build a schema for the following class structure:
```

sealed trait InnerTrait
case class InnerTraitConcrete(v: Int) extends InnerTrait
case class InnerTraitConcrete2(v: Int) extends InnerTrait

case class Inner(t: InnerTrait)
case class Outer(inners: Seq[Inner])
```

The schema generated for class `Outer` is the following:
```
{
  "type" : "record",
  "name" : "Outer",
  "namespace" : "com.strike.core",
  "fields" : [ {
    "name" : "inners",
    "type" : {
      "type" : "array",
      "items" : {
        "type" : "record",
        "name" : "Inner",
        "fields" : [ {
          "name" : "t",
          "type" : [ {
            "type" : "record",
            "name" : "InnerTraitConcrete",
            "fields" : [ {
              "name" : "v",
              "type" : "int"
            } ]
          }, {
            "type" : "record",
            "name" : "InnerTraitConcrete2",
            "fields" : [ {
              "name" : "v",
              "type" : "int"
            } ]
          } ]
        } ]
      }
    }
  } ]
}
```
but when serializing and deserializing an instance of class `Outer`, I have the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: ExtractAvroSchema$$anon$10/decode$$anon
	at ExtractAvroSchema$$anon$10$anon$applyMacro$macro$45$1$$anon$11.decode(ExtractAvroSchema.scala:32)
	at ExtractAvroSchema$$anon$10$anon$applyMacro$macro$45$1$$anon$11.decode(ExtractAvroSchema.scala:32)
	at com.sksamuel.avro4s.Decoder$$anon$10.$anonfun$decode$9(Decoder.scala:232)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.sksamuel.avro4s.Decoder$$anon$10.decode(Decoder.scala:232)
	at com.sksamuel.avro4s.Decoder$$anon$10.decode(Decoder.scala:226)
	at com.sksamuel.avro4s.Decoder$.decodeFieldOrApplyDefault(Decoder.scala:470)
	at com.sksamuel.avro4s.Decoder$.decodeFieldOrApplyDefaultLazy(Decoder.scala:434)
	at ExtractAvroSchema$$anon$10.decode(ExtractAvroSchema.scala:32)
	at ExtractAvroSchema$$anon$10.decode(ExtractAvroSchema.scala:32)
	at com.sksamuel.avro4s.AvroJsonInputStream.$anonfun$iterator$4(AvroJsonInputStream.scala:26)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:455)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:309)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:307)
	at scala.collection.AbstractIterator.to(Iterator.scala:1425)
	at scala.collection.TraversableOnce.toSet(TraversableOnce.scala:303)
	at scala.collection.TraversableOnce.toSet$(TraversableOnce.scala:303)
	at scala.collection.AbstractIterator.toSet(Iterator.scala:1425)
	at ExtractAvroSchema$.delayedEndpoint$com$...$core$ExtractAvroSchema$1(ExtractAvroSchema.scala:33)
	at ExtractAvroSchema$delayedInit$body.apply(ExtractAvroSchema.scala:18)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at ExtractAvroSchema$.main(ExtractAvroSchema.scala:18)
	at ExtractAvroSchema.main(ExtractAvroSchema.scala)
Caused by: java.lang.ClassNotFoundException: ExtractAvroSchema$$anon$10.decode$$anon
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 44 more
```

Thank you

**Comment by RomanBrodetski** [comment]
doesn't work with 2.0.4 and 2.0.3
works with 2.0.2

**Comment by sksamuel** [comment]
Seems ok in 2.0.4 and in master.

See test which I've added here: https://github.com/sksamuel/avro4s/commit/1d140944993a85f68d494cd3b53d970e622907a2

Travis build here:
https://travis-ci.org/sksamuel/avro4s/builds/487459347
