### ISSUE TITLE
JsonToAvroConverter is throwing error for empty arrays

### ISSUE THREAD

**Issue by ivanobulo** [sksamuel/avro4s#297]
Example:
```
new JsonToAvroConverter("test").convert("Name",
        """
          |{"EmptyArray": []}
        """.stripMargin)
```
The error is:
```
head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:431)
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at com.sksamuel.avro4s.json.JsonToAvroConverter.convert(JsonToAvroConverter.scala:39)
	at com.sksamuel.avro4s.json.JsonToAvroConverter$$anonfun$1.apply(JsonToAvroConverter.scala:53)
	at com.sksamuel.avro4s.json.JsonToAvroConverter$$anonfun$1.apply(JsonToAvroConverter.scala:53)
```
I think array of `Schema.Type.NULL` would be appropriate for this field.

**Comment by sksamuel** [comment]
Can you try the 3.0.x snapshot from
https://oss.sonatype.org/content/repositories/snapshots/com/sksamuel/avro4s
This is a new version and is available for 2.11 and 2.22
