### ISSUE TITLE
Invalid macros for SchemaFor with Record having Option of Record with ADT

### ISSUE THREAD

**Issue by klass-ivan** [sksamuel/avro4s#334]
```
import com.sksamuel.avro4s.SchemaFor

sealed trait Adt
case object One extends Adt
case object Two extends Adt

case class Example(adt: Adt)
case class HasOption(opt: Option[Example])

SchemaFor[HasOption]
```
causes
```
java.lang.NoClassDefFoundError: $anon$1/_schema $$anon
  ... 30 elided
Caused by: java.lang.ClassNotFoundException: $anon$1._schema $$anon
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:72)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 30 more
```

But the following works (we keep same derivation rules, but factor out part of the macro into companion object) :
```
import com.sksamuel.avro4s.SchemaFor

sealed trait Adt
case object One extends Adt
case object Two extends Adt

case class Example(adt: Adt); object Example {
  implicit val schemaFor: SchemaFor[Example] = com.sksamuel.avro4s.SchemaFor.applyMacro
}
case class HasOption(opt: Option[Example])

SchemaFor[HasOption]
```
outputs `com.sksamuel.avro4s.SchemaFor[HasOption] = $anon$1@6165ac45`

**Comment by klass-ivan** [comment]
@sksamuel I've fixed it for 2.0.4 in https://github.com/invitae/avro4s/commit/df0a7e1d12063d58791e6b38b227740d1356ac6b
If you don't mind, could you please add a 2.0 branch so I can submit a PR for 2.0.5 with that fix?

**Comment by sksamuel** [comment]
Branch created.

**Comment by klass-ivan** [comment]
@sksamuel thank you!
