### ISSUE TITLE
User defined classes can't be used as defaults in a Union

### ISSUE THREAD

**Issue by bobbyrauchenberg** [sksamuel/avro4s#352]
Currently it's not possible to use a user defined class as a default value in a Union

For this ADT
```
sealed trait Dog
case object HotDog extends Dog
case class CupcatDog(name: String) extends Dog
```

For this case class
```
case class Cupcat(dog: Dog = HotDog)
```

This test
```
"support default value of an arbitrary type" in {
      val schema = AvroSchema[Cupcat]
      val expected = new org.apache.avro.Schema.Parser().parse(getClass.getResourceAsStream("/optional_default_values.json"))
      schema.toString(true) shouldBe expected.toString(true)
    }
```
Throws 
```
Unknown datum class: class com.sksamuel.avro4s.schema.CupcatDog
org.apache.avro.AvroRuntimeException: Unknown datum class: class com.sksamuel.avro4s.schema.CupcatDog
	at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
	at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
	at org.apache.avro.Schema$Field.<init>(Schema.java:530)
	at com.sksamuel.avro4s.SchemaFor$.com$sksamuel$avro4s$SchemaFor$$buildField(SchemaFor.scala:246)
	at com.sksamuel.avro4s.SchemaFor$$anon$14.$anonfun$schema$9(SchemaFor.scala:305)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:39)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.sksamuel.avro4s.SchemaFor$$anon$14.schema(SchemaFor.scala:282)
	at com.sksamuel.avro4s.AvroSchema$.apply(AvroSchema.scala:21)
	at com.sksamuel.avro4s.schema.DefaultValueSchemaTest.$anonfun$new$65(DefaultValueSchemaTest.scala:59)
```

In the spec it says that the default for a record is encoded as a json object

https://avro.apache.org/docs/1.8.2/spec.html?origin_team=T02GEFU92#schema_primitive

I'd be happy to pick up looking at this if it helps?

**Comment by sksamuel** [comment]
Released 3.0.0 final which contains your fix for this.
