### ISSUE TITLE
Error using library with confluent kafka deserializer

### ISSUE THREAD

**Issue by ikilledthecat** [sksamuel/avro4s#380]
I'm trying to use the akka streams project(alpakka-kafka connector) to process some data from a kafka topic. I'm using the confluent schema registry. Unfortunately, I'm unable to initialize a deserializer object if I include the avro4s 3.x library. avro4s 2.x and 1.x have no problems.
Minimal Example:

build.sbt
```
name := "akka-quickstart-scala"

version := "1.0"

scalaVersion := "2.12.8"

lazy val akkaVersion = "2.5.25"

resolvers += "Confluent Maven Repository" at "https://packages.confluent.io/maven/"

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-stream-kafka" % "1.0.5",
  "com.sksamuel.avro4s" %% "avro4s-core" % "3.0.1",
  "io.confluent" % "kafka-avro-serializer" % "5.0.1",
)

```

Main.scala
```
import io.confluent.kafka.serializers.KafkaAvroDeserializer

object Main extends App  {
  val kafkaAvroDeserializer = new KafkaAvroDeserializer
}
```
Code will compile but running it results in:

```
[error] java.lang.NoClassDefFoundError: org/codehaus/jackson/JsonNode
[error]         at Main$.delayedEndpoint$Main$1(Main.scala:4)
[error]         at Main$delayedInit$body.apply(Main.scala:3)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at Main$.main(Main.scala:3)
[error]         at Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.JsonNode
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at Main$.delayedEndpoint$Main$1(Main.scala:4)
[error]         at Main$delayedInit$body.apply(Main.scala:3)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at Main$.main(Main.scala:3)
[error]         at Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by ikilledthecat** [comment]
Figured out the error lies with the confluent library so closing this.
Link to issue on confluent library in case someone else chases this problem: https://github.com/confluentinc/schema-registry/issues/1222
