### ISSUE TITLE
Error while resolving default non-optional value of type Int

### ISSUE THREAD

**Issue by seveneves** [sksamuel/avro4s#381]
The following data model generates an error while schema retrieval

```scala
import com.sksamuel.avro4s.{DefaultFieldMapper, SchemaFor}

case class Node(leaf: Leaf = Leaf())
case class Leaf(someInt: Int = 0)
SchemaFor[Node].schema(DefaultFieldMapper)
```

The error is 

```
Unknown datum class: class scala.math.BigInt
org.apache.avro.AvroRuntimeException: Unknown datum class: class scala.math.BigInt
	at `util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
	at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:63)
	at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
	at org.apache.avro.Schema$Field.<init>(Schema.java:560)
	at com.sksamuel.avro4s.SchemaFor$.com$sksamuel$avro4s$SchemaFor$$buildField(SchemaFor.scala:244)
	at com.sksamuel.avro4s.SchemaFor$$anon$14.$anonfun$schema$3(SchemaFor.scala:306)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:39)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.sksamuel.avro4s.SchemaFor$$anon$14.schema(SchemaFor.scala:283)
```

Version used are 

```sbt
libraryDependencies += "com.sksamuel.avro4s" %% "avro4s-core"            % "3.0.1"
```

The error seems to be related to default value of `Leaf()` or `Some(Leaf(0))` calculation in code `com.sksamuel.avro4s.CustomDefaults`

```scala
  def customDefault(p: Product, schema: Schema): CustomDefault =
    if(isEnum(p, schema.getType))
      CustomEnumDefault(trimmedClassName(p))
    else {
      if(isUnionOfEnum(schema)) {
        val enumType = schema.getTypes.asScala.filter(_.getType == Schema.Type.ENUM).head
        CustomUnionWithEnumDefault(enumType.getName, trimmedClassName(p), p.toString)
      } else
        CustomUnionDefault(trimmedClassName(p), parse(write(p)).extract[Map[String, Any]].asJava)
    }
```

` parse(write(p))` is calling 

```scala  
def parse(in: JsonInput, useBigDecimalForDouble: Boolean = false, useBigIntForLong: Boolean = true): JValue = in match {
    case StringInput(s) => JsonParser.parse(s, useBigDecimalForDouble, useBigIntForLong)
    case ReaderInput(rdr) => JsonParser.parse(rdr, useBigDecimalForDouble = useBigDecimalForDouble, useBigIntForLong = useBigIntForLong)
    case StreamInput(stream) => JsonParser.parse(Source.fromInputStream(stream).bufferedReader(), useBigDecimalForDouble = useBigDecimalForDouble, useBigIntForLong = useBigIntForLong)
    case FileInput(file) => JsonParser.parse(Source.fromFile(file).bufferedReader(), useBigDecimalForDouble = useBigDecimalForDouble, useBigIntForLong = useBigIntForLong)
  }
```

 and this code reads `0` as `BigInt` and `BigInt`s are not supported by `org.apache.avro`

**Comment by sksamuel** [comment]
Added a fix to master.
