### ISSUE TITLE
Decoder for Scala enum is not serializable

### ISSUE THREAD

**Issue by paoloboni** [sksamuel/avro4s#484]
Hi, I'm using Avro4s with Flink, and it would be very useful to make the Decoder for Scala enumeration serializable.

Example:
```
import WeekDay.WeekDay
import com.sksamuel.avro4s.Decoder

object WeekDay extends Enumeration {
  type WeekDay = Value
  val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value
}

object TestApp extends App {
  org.apache.flink.util.InstantiationUtil.serializeObject(Decoder[WeekDay])
}
```

Result:
```
Exception in thread "main" java.io.NotSerializableException: scala.reflect.runtime.JavaMirrors$JavaMirror
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:586)
	at TestApp$.delayedEndpoint$com$elevenfs$transactions$serdes$TestApp$1(TestApp.scala:12)
	at TestApp$delayedInit$body.apply(TestApp.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at TestApp$.main(TestApp.scala:11)
	at TestApp.main(TestApp.scala)
```

Would it make sense to mark this field as transient lazy val: https://github.com/sksamuel/avro4s/blob/f8d40e4587a65dbed444e0631230ccc6076d357f/avro4s-core/src/main/scala/com/sksamuel/avro4s/Decoder.scala#L343

**Comment by andreas-schroeder** [comment]
Hi @paoloboni, thanks for reporting this issue! This will get fixed soon I hope.
