### ISSUE TITLE
Decoder for shapeless Coproduct is not serializable

### ISSUE THREAD

**Issue by paoloboni** [sksamuel/avro4s#485]
Hi, I'm using Avro4s with Flink, and I think it would be very useful to make the Decoder for Scala shapeless coproduct serializable.

Example:
```
import com.sksamuel.avro4s.Decoder
import shapeless.{:+:, CNil}

object TestApp extends App {
  type ISB = Int :+: String :+: Boolean :+: CNil
  org.apache.flink.util.InstantiationUtil.serializeObject(Decoder[ISB])
}
```

Result:
```
Exception in thread "main" java.io.NotSerializableException: com.sksamuel.avro4s.SafeFrom$$anon$2
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:586)
	at TestApp$.delayedEndpoint$com$elevenfs$transactions$serdes$TestApp$1(TestApp.scala:8)
	at TestApp$delayedInit$body.apply(TestApp.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at TestApp$.main(TestApp.scala:6)
	at TestApp.main(TestApp.scala)
```

Would it make sense to simply make `com.sksamuel.avro4s.SafeFrom` serializable?

**Comment by andreas-schroeder** [comment]
Hi @paoloboni, thanks for reporting this one too!
