### ISSUE TITLE
serialization fails with named values in enums

### ISSUE THREAD

**Issue by mdespriee** [sksamuel/avro4s#502]
Using scala 2.13.1, avro4s-core 3.1.1

When naming values in enums, the serializer fails with:
```
java.lang.NullPointerException: null of com.sencrop.serialization.NamedEnum in field m of com.sencrop.serialization.Foo
	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:183)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:177)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:72)
	at com.sksamuel.avro4s.DefaultAvroOutputStream.write(DefaultAvroOutputStream.scala:22)
 ...
Caused by: java.lang.NullPointerException
	at org.apache.avro.Schema$EnumSchema.getEnumOrdinal(Schema.java:1025)
	at org.apache.avro.generic.GenericDatumWriter.writeEnum(GenericDatumWriter.java:219)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:133)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:206)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:195)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:130)
	... 54 more
```

Reproducer:
```

import com.sksamuel.avro4s.{AvroOutputStream, SchemaFor}
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

object ClassicEnum extends Enumeration {
  val T = Value
}
case class Bar(m: ClassicEnum.Value)

object NamedEnum extends Enumeration {
  val T = Value("Temperature")
}
case class Foo(m: NamedEnum.Value)

class BugDemo extends AnyFlatSpec with Matchers {

  "serialize" should "work with classic enum" in {
    println(SchemaFor[Bar].schema.toString(true))
    val byteStr = new java.io.ByteArrayOutputStream
    val avroStr = AvroOutputStream.binary[Bar].to(byteStr).build()
    avroStr.write(Bar(ClassicEnum.T)) // passes
  }

  "serialize" should "work with named values" in {
    println(SchemaFor[Foo].schema.toString(true))
    val byteStr = new java.io.ByteArrayOutputStream
    val avroStr = AvroOutputStream.binary[Foo].to(byteStr).build()
    avroStr.write(Foo(NamedEnum.T)) // fails
  }
}
```

**Comment by andreas-schroeder** [comment]
Yes, the classic Scala Enumerations don't get much attention. The behavior you are seeing is related to the default encoder/decoder using the val's names via reflection instead of calling toString on them; see [here](https://github.com/sksamuel/avro4s/blob/master/avro4s-core/src/main/scala/com/sksamuel/avro4s/BaseTypes.scala#L97). I've tried to spike a fix for your issue briefly, but didn't succeed. 

Do you want to give it a try?

As a workaround for your issue, you could write a custom SchemaFor, Encoder, and Decoder for the enum you need.

**Comment by sksamuel** [comment]
I had a go here: https://github.com/sksamuel/avro4s/pull/534

**Comment by DanMaly** [comment]
Hi @sksamuel, we are currently being hit hard by this bug. I wonder if I could help get your change merged? I understand there were some failing tests?
