### ISSUE TITLE
Issue with encoder for optional shapeless coproduct

### ISSUE THREAD

**Issue by kpmeen** [sksamuel/avro4s#505]
The last few days I've been trying to get a very basic schema using an optional coproduct to work as expected, without success. I’m using avro4s 3.1.1 with Scala 2.12.11 and have set the `-Xsource:2.13` flag.

Given the following data model

```scala
type SimpleCo = Array[Byte] :+: String :+: CNil

case class Simple(v: Option[SimpleCo] = None)
```

When I create an instance of `SchemaFor[Simple]`, I get the expected Avro schema for the class.

```scala
implicit val simpleSchemaFor = SchemaFor.gen[Simple]

println(simpleSchemaFor.schema.toString(true))
```

Will print the schema

```json
{
  "type" : "record",
  "name" : "Simple",
  "namespace" : "simple",
  "fields" : [ {
    "name" : "v",
    "type" : [ "null", "bytes", "string" ],
    "default" : null
  } ]
}
```

When I try to actually serialize the following instance of `Simple` with a coproduct value of `Array[Byte]` I get the following error:

```
UnresolvedUnionException: Not in union ["null",{"type":"array","items":"int"},"string"]
```

Which implies that the type of the `Array[Byte]` in the schema generated for the `Encoder[Simple]` does not result in the same (correct) schema as the `SchemaFor[Simple]` generates.

I verified this by explicitly setting up and `Encoder[Simple]` to inspect the Schema, which results in:

```json
{
  "type" : "record",
  "name" : "Simple",
  "namespace" : "simple",
  "fields" : [ {
    "name" : "v",
    "type" : [ "null", {
      "type" : "array",
      "items" : "int"
    }, "string" ],
    "default" : null
  } ]
}
```

I then tried to create an instance of the the encoder using the `SchemaFor[Simple]` that I defined previously:

```scala
implicit val simpleSchemaFor = SchemaFor.gen[Simple]
implicit val simpleEncoder = Encoder.gen[Simple].withSchema(simpleSchemaFor)
```

Which then throws the following exception:

```
org.apache.avro.AvroRuntimeException: Not a union: "bytes"
at org.apache.avro.Schema.getTypes(Schema.java:366)
at com.sksamuel.avro4s.ShapelessCoproducts$.takeFirstType(ShapelessCoproducts.scala:102)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4.$anonfun$encoder$1(ShapelessCoproducts.scala:39)
at com.sksamuel.avro4s.EncoderHelpers$.mapFullUpdate(Encoder.scala:137)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4.encoder(ShapelessCoproducts.scala:39)
at com.sksamuel.avro4s.Encoder.resolveEncoder(Encoder.scala:60)
at com.sksamuel.avro4s.Encoder.resolveEncoder$(Encoder.scala:59)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4.resolveEncoder(ShapelessCoproducts.scala:37)
at com.sksamuel.avro4s.CollectionAndContainerEncoders$$anon$7.encoder(CollectionsAndContainers.scala:74)
at com.sksamuel.avro4s.Encoder.resolveEncoder(Encoder.scala:60)
at com.sksamuel.avro4s.Encoder.resolveEncoder$(Encoder.scala:59)
at com.sksamuel.avro4s.CollectionAndContainerEncoders$$anon$7.resolveEncoder(CollectionsAndContainers.scala:72)
at com.sksamuel.avro4s.RecordFields$FieldEncoder.apply(RecordFields.scala:36)
at com.sksamuel.avro4s.Records$.$anonfun$encoder$1(Records.scala:90)
at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:280)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
at scala.collection.TraversableLike.flatMap(TraversableLike.scala:280)
at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:277)
at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
at com.sksamuel.avro4s.Records$.encoder(Records.scala:88)
at com.sksamuel.avro4s.RecordEncoder.withSchema(Records.scala:32)
at com.sksamuel.avro4s.ResolvableEncoder.withSchema(Encoder.scala:97)
at com.sksamuel.avro4s.ResolvableEncoder.withSchema$(Encoder.scala:97)
at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.withSchema(MagnoliaDerived.scala:54)
... 36 elided
```

The last line in the error about `MagnoliaDerivedEncoders` made me wonder if there are issues with some implicit resolutions here. So I added the following implicits to help out with the resolution

```scala
implicit val cosf = SchemaFor[SimpleCo]
implicit val ocosf = SchemaFor.optionSchemaFor(cosf)
implicit val cEnc = Encoder[SimpleCo].withSchema(cosf)
implicit val ocEnc = Encoder.optionEncoder[SimpleCo].withSchema(ocosf)
```

That seems to have fixed the use of the Magnolia implicits. But now I get this error:

```
cosf: com.sksamuel.avro4s.SchemaFor[SimpleCo] = com.sksamuel.avro4s.ShapelessCoproductSchemaFors$$anon$2@c2f38c2
ocosf: com.sksamuel.avro4s.SchemaFor[Option[SimpleCo]] = com.sksamuel.avro4s.CollectionAndContainerSchemaFors$$anon$1@195b6cd6
cEnc: com.sksamuel.avro4s.Encoder[SimpleCo] = com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4$$anon$5@55a06d86
org.apache.avro.AvroRuntimeException: Not a union: "bytes"
at org.apache.avro.Schema.getTypes(Schema.java:366)
at com.sksamuel.avro4s.ShapelessCoproducts$.takeFirstType(ShapelessCoproducts.scala:102)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4.$anonfun$encoder$1(ShapelessCoproducts.scala:39)
at com.sksamuel.avro4s.EncoderHelpers$.mapFullUpdate(Encoder.scala:137)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4.encoder(ShapelessCoproducts.scala:39)
at com.sksamuel.avro4s.Encoder.resolveEncoder(Encoder.scala:60)
at com.sksamuel.avro4s.Encoder.resolveEncoder$(Encoder.scala:59)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4.resolveEncoder(ShapelessCoproducts.scala:37)
at com.sksamuel.avro4s.EncoderHelpers$.buildWithSchema(Encoder.scala:134)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4$$anon$5.withSchema(ShapelessCoproducts.scala:51)
at com.sksamuel.avro4s.Encoder.resolveEncoder(Encoder.scala:61)
at com.sksamuel.avro4s.Encoder.resolveEncoder$(Encoder.scala:59)
at com.sksamuel.avro4s.ShapelessCoproductEncoders$$anon$4$$anon$5.resolveEncoder(ShapelessCoproducts.scala:41)
at com.sksamuel.avro4s.CollectionAndContainerEncoders$$anon$7.encoder(CollectionsAndContainers.scala:74)
at com.sksamuel.avro4s.Encoder.resolveEncoder(Encoder.scala:60)
at com.sksamuel.avro4s.Encoder.resolveEncoder$(Encoder.scala:59)
at com.sksamuel.avro4s.CollectionAndContainerEncoders$$anon$7.resolveEncoder(CollectionsAndContainers.scala:72)
at com.sksamuel.avro4s.EncoderHelpers$.buildWithSchema(Encoder.scala:134)
at com.sksamuel.avro4s.CollectionAndContainerEncoders$$anon$7$$anon$8.withSchema(CollectionsAndContainers.scala:83)
at com.sksamuel.avro4s.ResolvableEncoder.withSchema(Encoder.scala:97)
at com.sksamuel.avro4s.ResolvableEncoder.withSchema$(Encoder.scala:97)
at com.sksamuel.avro4s.CollectionAndContainerEncoders$$anon$7.withSchema(CollectionsAndContainers.scala:72)
... 36 elided
```

Is this a bug in avro4s? Am I doing something wrong?
Any help would be greatly appreciated!!!

NOTE: The code works as expected when if I replace the `Option[SimpleCo]` with just `SimpleCo`. But I really need it to be an optional field with a default `null` value.

**Comment by kpmeen** [comment]
When creating a wrapper class for the coproduct, and making the wrapper optional, like this:

```
type SimpleCo = String :+: Array[Byte] :+: CNil

case class CoWrapper(co: SimpleCo)

case class Simple(coWrapper: Option[CoWrapper] = None)
```

The generated Avro schema is as expected with nested union types:

```
{
  "type" : "record",
  "name" : "Simple",
  "namespace" : "simple",
  "fields" : [ {
    "name" : "coWrapper",
    "type" : [ "null", {
      "type" : "record",
      "name" : "CoWrapper",
      "namespace" : "simple",
      "fields" : [ {
        "name" : "co",
        "type" : [ "string", "bytes" ]
      } ]
    } ],
    "default" : null
  } ]
}
```

Instances `Simple(Some(CoWrapper(Coproduct[SimpleCo]("simple2".getBytes))))` are also successfully serialized.

The problem _only_ arises when the coproduct is optional.

**Comment by kpmeen** [comment]
anyone?

**Comment by andreas-schroeder** [comment]
Hi @kpmeen ,

Sorry for the late reply, I think both issues are indeed bugs, I will come back to you with more details. 

The version 3.1.1 you are using is actually from the new 4.0.x (not by intention), so you may want to try an earlier version - the issue might have been introduced in the new codebase.

**Comment by andreas-schroeder** [comment]
Hi @kpmeen, your issue is indeed due to a bug, the Encoder/Decoder for byte arrays are using the wrong schema. My advice would be to use an earlier version until avro4s has a proper 4.0.x release.

**Comment by kpmeen** [comment]
Thanks @andreas-schroeder, which version would you suggest I down-grade to?

**Comment by andreas-schroeder** [comment]
You can now try 4.0.0-RC1 actually, the fix is included there

**Comment by kpmeen** [comment]
Ok 🙂  I'll give it a shot!

**Comment by kpmeen** [comment]
Yes!!! 4.0.0-RC1 worked perfectly 😁 
Thank you @andreas-schroeder!!!!
