### ISSUE TITLE
Failed to construct kafka consumer/producer: Could not find a public no-argument constructor for com.sksamuel.avro4s.kafka.GenericSerde

### ISSUE THREAD

**Issue by irenkamalova** [sksamuel/avro4s#511]
I'm trying to use it for Kafka, following documentation, here is my example: https://github.com/irenkamalova/kafka-with-avro/tree/master/src/main/scala
However, it doesn't work:
```scala
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:825)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646)
	at Consumer$.consumeFromKafka(Consumer.scala:16)
	at Consumer$.main(Consumer.scala:11)
	at Consumer.main(Consumer.scala)
Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for com.sksamuel.avro4s.kafka.GenericSerde
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:310)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:370)
	at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:392)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:722)
	... 5 more
Caused by: java.lang.NoSuchMethodException: com.sksamuel.avro4s.kafka.GenericSerde.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:308)

```

Is it smth wrong that I'm doing?

**Comment by andreas-schroeder** [comment]
Can you share the code that produces the error? I'm not seeing code that would produce that error. Still, I suspect that you are trying to create a GenericSerde via reflection (specified in properties), but that can't work with avro4s' GenericSerde

**Comment by irenkamalova** [comment]
Sure (it was in "init commit" :))
```scala
import java.time.Duration
import java.util

import org.apache.kafka.clients.consumer.KafkaConsumer

import scala.collection.JavaConverters._

object Consumer {

  def main(args: Array[String]): Unit = {
    consumeFromKafka()
  }
  def consumeFromKafka(): Unit = {

    val props = KafkaProperties.props
    val consumer: KafkaConsumer[String, Object] = new KafkaConsumer[String, Object](props)
    consumer.subscribe(util.Arrays.asList(KafkaProperties.topic))
    while (true) {
      val record = consumer.poll(Duration.ofMillis(1000)).asScala
      for (data <- record.iterator) {
        println(data.key())
        println(data.value())
      }
    }
  }
}

```
sbt:
```scala
name := "connect-to-kafka"

version := "0.1"

scalaVersion := "2.12.11"

libraryDependencies += "org.apache.kafka" %% "kafka" % "2.4.1"
// https://mvnrepository.com/artifact/com.sksamuel.avro4s/avro4s-kafka
libraryDependencies += "com.sksamuel.avro4s" %% "avro4s-kafka" % "3.0.0-RC1"

libraryDependencies += "com.typesafe" % "config" % "1.4.0"
```

**Comment by sksamuel** [comment]
What serializers are you using in your kafka props ?

**Comment by irenkamalova** [comment]
Here is my properties for kafka:
```scala
import java.io.File
import java.util.Properties

import com.sksamuel.avro4s.kafka.GenericSerde
import com.typesafe.config.ConfigFactory
import org.apache.kafka.clients.CommonClientConfigs
import org.apache.kafka.clients.consumer.ConsumerConfig
import org.apache.kafka.clients.producer.ProducerConfig
import org.apache.kafka.common.serialization.{StringDeserializer, StringSerializer}

object KafkaProperties {
  val config = ConfigFactory.parseFile(new File("application.conf")).getConfig("KafkaConfig.kafka")
  val dataSerde2 = new GenericSerde[Seq[Record]]
  val topic = config.getString("topic")
  val props = new Properties()
  props.put(CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG, config.getString(CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG))
  props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, classOf[StringSerializer])
  props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, dataSerde2.getClass)
  props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, classOf[StringDeserializer])
  props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, dataSerde2.getClass)
  props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, config.getString(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG))
  props.put(ConsumerConfig.GROUP_ID_CONFIG, config.getString(ConsumerConfig.GROUP_ID_CONFIG))
  def getProps: Properties = props
}
```

**Comment by sksamuel** [comment]
My advice would be to subclass GenericSerde and call the constructor with the AvroFormat you want to deserialize. Then you can reference this subclass in your props, and it would work because it will have a zero arg constructor.
