### ISSUE TITLE
ByteDecode with java.lang.ClassCastException in version 3.0.0-RC2

### ISSUE THREAD

**Issue by josevi96** [sksamuel/avro4s#530]
Using a case class like this one:
```
case class ByteExample(id: String, `type`: String, value: ByteValue)
case class ByteValue(value: Byte, date: MyDate)
```
The ByteDecoder:
```
 implicit object ByteDecoder extends Decoder[Byte] {
    override def decode(value: Any, schema: Schema)(implicit naming: NamingStrategy = DefaultNamingStrategy): Byte = value.asInstanceOf[Int].toByte
  }
```
this causes a call to the function unboxToInt in scala.runtime.BoxesRunTime.
```
public static int unboxToInt(Object i) {
   return i == null ? 0 : ((java.lang.Integer)i).intValue();
 } 
```
the Object _"i"_  is of type scala.Byte and when we try to cast it into a java.lang.Integer we have this exception:
```
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
   at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
   at com.sksamuel.avro4s.Decoder$ByteDecoder$.decode(Decoder.scala:79)
   at com.sksamuel.avro4s.Decoder$ByteDecoder$.decode(Decoder.scala:78)
   at com.sksamuel.avro4s.Decoder$$anon$11$$anonfun$11.apply(Decoder.scala:382)
   at com.sksamuel.avro4s.Decoder$$anon$11$$anonfun$11.apply(Decoder.scala:366)
   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
   at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
```
We found this issue making a test like this one:

```
"ByteExample" should {
    "encode/decode to generic record" in {
          val format = RecordFormat[ByteExample]
          val encodedRecord: GenericRecord = format.to(byteEvent)
          val decodedEvent: ByteExample = format.from(encodedRecord)
          decodedEvent mustEqual byteEvent
    }
}
```

I make a fork from this repo and i commit the changes, you can see it in this [link](https://github.com/josevi96/avro4s/commit/e69c41b72dbf6fcfcc77c44958294034f02c5b2e)
I'm sorry if I made a mistake, it is my first issue, thank you very much for your attention

**Comment by sksamuel** [comment]
Do you mean 4.0.0-RC2 or actually 3 ?

**Comment by josevi96** [comment]
i mean the 3.0.0-RC2 with scala 2.11.12

**Comment by sksamuel** [comment]
The last release for 2.11 was nearly 3 years ago and has been end of life for a long time. I'm afraid the library no longer supports 2.11.
