### ISSUE TITLE
Type guarded decoding is not in the correct order

### ISSUE THREAD

**Issue by sebastian-ziegler** [sksamuel/avro4s#545]
Hello!

I was trying to decode a case class, one of the attributes of that case class got the type `Either[String, Map[String, String]]` when I found the Decoder generated was `Either[StringDecoder, ArrayDecoder]` instead of being `Either[StringDecoder, MapDecoder]`, thanks to this the data I was trying to deserialise was failing with this error:

```
2020-09-02 15:39:20.051 ERROR - MaterializedView: com.sksamuel.avro4s.Avro4sDecodingException: Unable to decode value '{id=5348024557502465}'
	at com.sksamuel.avro4s.ShapelessCoproductDecoders$$anon$6.decode(ShapelessCoproducts.scala:64)
	at com.sksamuel.avro4s.ShapelessCoproductDecoders$$anon$6.decode(ShapelessCoproducts.scala:61)
	at com.sksamuel.avro4s.ShapelessCoproductDecoders$$anon$7$$anon$8.decode(ShapelessCoproducts.scala:82)
	at com.sksamuel.avro4s.ShapelessCoproductDecoders$$anon$7$$anon$8.decode(ShapelessCoproducts.scala:75)
	at com.sksamuel.avro4s.ShapelessCoproductDecoders$$anon$7$$anon$8.decode(ShapelessCoproducts.scala:82)
	at com.sksamuel.avro4s.ShapelessCoproductDecoders$$anon$7$$anon$8.decode(ShapelessCoproducts.scala:75)
	at com.sksamuel.avro4s.CollectionAndContainerDecoders$$anon$26$$anon$27.$anonfun$decode$7(CollectionsAndContainers.scala:288)
	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
	at scala.collection.immutable.HashMap.map(HashMap.scala:39)
	at com.sksamuel.avro4s.CollectionAndContainerDecoders$$anon$26$$anon$27.decode(CollectionsAndContainers.scala:288)
	at com.sksamuel.avro4s.CollectionAndContainerDecoders$$anon$26$$anon$27.decode(CollectionsAndContainers.scala:284)
	at com.sksamuel.avro4s.RecordFields$FieldDecoder$ValueDecoder.tryDecode(RecordFields.scala:78)
	at com.sksamuel.avro4s.RecordFields$FieldDecoder$ValueDecoder.fastDecodeFieldValue(RecordFields.scala:59)
	at com.sksamuel.avro4s.RecordDecoder.decode(Records.scala:51)
	at com.sksamuel.avro4s.ResolvableDecoder.decode(Decoder.scala:95)
	at com.sksamuel.avro4s.ResolvableDecoder.decode$(Decoder.scala:95)
	at com.sksamuel.avro4s.MagnoliaDerivedDecoders$$anon$6.decode(MagnoliaDerived.scala:80)
	at com.sksamuel.avro4s.AvroDataInputStream$$anon$1.next(AvroDataInputStream.scala:29)
	at com.sksamuel.avro4s.kafka.GenericSerde.deserialize(GenericSerde.scala:37)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
	at com.sksamuel.avro4s.kafka.GenericSerde.deserialize(GenericSerde.scala:16)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1306)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3500(Fetcher.java:128)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1537)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1373)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:679)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:634)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1313)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
```

The data I was trying to decode looks like this:
```
{
    "metadata": {
        "time": "2020-09-02T18:52:42Z",
        "keys": {
            "id": "5348024557502465"
        },
        "UUID": "30d5d307-4801-44ca-bd3a-de189f47207d"
    },
    "payload": null
}
```

And the schema I was expecting to use looks like this:

```
{
	"namespace": "com.sebastian.broker",
	"type": "record",
	"name": "BrokerWrapper",
	"fields": [
		{
			"name": "metadata",
			"type": {"type": "map", "values": ["string", {"type": "map", "values": "string"}]}
		},
		{
			"name": "payload",
			"type": ["null", "bytes"],
			"default": null
		}

	]
}
```

Looking at the code also found this in `TypeGuardedDecoding.scala`

```
...
else if (tpe <:< typeOf[Array[_]] || tpe <:< typeOf[java.util.Collection[_]] || tpe <:< typeOf[Iterable[_]]) {
      arrayDecoder(decoder)
    } else if (tpe <:< typeOf[java.util.Map[_, _]] || tpe <:< typeOf[Map[_, _]]) {
      mapDecoder(decoder)
    } else if (tpe <:< typeOf[shapeless.Coproduct]) {
      coproductDecoder(decoder)
    }
...
```

The Map type check should be before the array type check, since maps are not going to get their own map decoder because every Java Map is part of `java.util.Collection[_]` and every scala map is part of `Iterable[_]`

**Comment by sebastian-ziegler** [comment]
I created also a fix in #546 since gave it a try and the scenario worked as expected.
