### ISSUE TITLE
NPE with Kafka-Tombstones (null values)

### ISSUE THREAD

**Issue by jessorlisa** [sksamuel/avro4s#552]
**Environment**
- Avro4s: v4.0.0
- KafkaStreams: v2.5.1
- Scala: v.2.13.2

**Code Sample**
```
//Kafka Key-Type: UUID
//Kafka Value-Type: Pattern
case class Pattern(regex:String)

[...]

val myStreamWhichContainsTombstones:KStream[UUID,Pattern] = ...
myStreamWhichContainsTombstones.to(myTopic) // raises NullPointerException if the Stream contains tombstone Records
val myGlobalKTable:GlobalKTable[UUID,Pattern] = builder.globalTable[UUID,Pattern](myTopic)
```

I need the Tombstone records because I need them in the GlobalKTable to delete entries.

If I extend the GenericSerde like shown below, it seems to be working as expected:

```
class FormattedGenericSerde[T >: Null : SchemaFor : Encoder : Decoder](avroFormat:AvroFormat) extends GenericSerde[T](avroFormat){
  override def serialize(topic: String, data: T): Array[Byte] = {
    if(data==null) null else super.serialize(topic,data)
  }
}
```

**Question: Would that be a reasonable solution?**

**NullPointerException**
```
java.lang.NullPointerException
	at magnolia.Param$$anon$4.dereference(interface.scala:212)
	at com.sksamuel.avro4s.RecordFields$FieldEncoder$ValueEncoder.encodeFieldValue(RecordFields.scala:17)
	at com.sksamuel.avro4s.RecordEncoder.encode(Records.scala:24)
	at com.sksamuel.avro4s.ResolvableEncoder.encode(Encoder.scala:93)
	at com.sksamuel.avro4s.ResolvableEncoder.encode$(Encoder.scala:93)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.encode(MagnoliaDerived.scala:54)
	at com.sksamuel.avro4s.DefaultAvroOutputStream.write(DefaultAvroOutputStream.scala:19)
	at com.sksamuel.avro4s.kafka.GenericSerde.serialize(GenericSerde.scala:57)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at com.sksamuel.avro4s.kafka.GenericSerde.serialize(GenericSerde.scala:16)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:176)
	at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:111)
	at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:92)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:133)
	at org.apache.kafka.streams.kstream.internals.KStreamMapValues$KStreamMapProcessor.process(KStreamMapValues.java:41)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.lambda$process$2(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:142)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:201)
	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:180)
	at org.apache.kafka.streams.kstream.internals.TimestampedCacheFlushListener.apply(TimestampedCacheFlushListener.java:45)
	at org.apache.kafka.streams.kstream.internals.TimestampedCacheFlushListener.apply(TimestampedCacheFlushListener.java:28)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$setFlushListener$1(MeteredKeyValueStore.java:119)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.putAndMaybeForward(CachingKeyValueStore.java:92)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.lambda$initInternal$0(CachingKeyValueStore.java:72)
	at org.apache.kafka.streams.state.internals.NamedCache.flush(NamedCache.java:151)
	at org.apache.kafka.streams.state.internals.NamedCache.flush(NamedCache.java:109)
	at org.apache.kafka.streams.state.internals.ThreadCache.flush(ThreadCache.java:124)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.flush(CachingKeyValueStore.java:272)
	at org.apache.kafka.streams.state.internals.WrappedStateStore.flush(WrappedStateStore.java:84)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$flush$7(MeteredKeyValueStore.java:192)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.flush(MeteredKeyValueStore.java:192)
	at org.apache.kafka.streams.processor.internals.ProcessorStateManager.flush(ProcessorStateManager.java:285)
	at org.apache.kafka.streams.processor.internals.AbstractTask.flushState(AbstractTask.java:177)
	at org.apache.kafka.streams.processor.internals.StreamTask.flushState(StreamTask.java:554)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:490)
	at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:478)
	at org.apache.kafka.streams.TopologyTestDriver.completeAllProcessableWork(TopologyTestDriver.java:517)
	at org.apache.kafka.streams.TopologyTestDriver.pipeRecord(TopologyTestDriver.java:472)
	at org.apache.kafka.streams.TopologyTestDriver.pipeRecord(TopologyTestDriver.java:806)
	at org.apache.kafka.streams.TestInputTopic.pipeInput(TestInputTopic.java:115)
	at org.apache.kafka.streams.TestInputTopic.pipeInput(TestInputTopic.java:137)
	at org.apache.kafka.streams.TestInputTopic.pipeKeyValueList(TestInputTopic.java:201)
	at de.lbbwam.evaluation.monitoring.IntegrationTestScalaUtils$.produceKeyValuesSynchronously(IntegrationTestScalaUtils.scala:129)
	at de.lbbwam.evaluation.monitoring.TopologySpec.$anonfun$new$106(TopologySpec.scala:201)
```

**Comment by andreas-schroeder** [comment]
Hi @jessorlisa , thanks for reporting, fix is on the way!

**Comment by sksamuel** [comment]
You can try 4.1.0.26-SNAPSHOT if you wish to test it.

**Comment by davideicardi** [comment]
What happen if we declare the stream with `KStream[UUID,Option[Pattern]]`?
From a semantic perspective we don't always have the value, so it is optional. Marking it as `Option` it is reasonable? It works with tombstones?

**Comment by cclp94** [comment]
Hello! Any idea when version 4.1.0 will be release? I have a kafka-streams app with some persisted ktables that would really benefit from this fix!

**Comment by sksamuel** [comment]
4.0.7 has just been released.
