### ISSUE TITLE
java.lang.ClassCastException: java.util.HashMap incompatible with org.apache.avro.generic.GenericRecord

### ISSUE THREAD

**Issue by mtekp** [sksamuel/avro4s#554]
I wanted to serialise Map to byteArray but its failing with ClassCastException
scala:`2.13.3`
java:`11 openjdk`

```scala
package avro.test

object Avro4sMap{
  import com.sksamuel.avro4s._
  import com.sksamuel.avro4s.Encoder._
  import java.io.ByteArrayOutputStream

  trait ToByteArray {
    def toByteArray(): Array[Byte]
  }

  def mapToByteArray[K, V](map: Map[K, V])(implicit valueEncoder: Encoder[Map[String,V]]): ToByteArray = {
    () => {
      val outputStream = new ByteArrayOutputStream()
      val os = AvroOutputStream.data[Map[String, V]].to(outputStream).build()
      val MapStringAsKey = map.map(x => x._1.toString -> x._2)
      os.write(MapStringAsKey)
      os.flush()
      val ba = outputStream.toByteArray
      os.close()
      ba
    }
  }

  def main(args: Array[String]): Unit = {
    println(mapToByteArray(Map("1" -> "hi")).toByteArray())
  }
}

```
```
Exception in thread "main" java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.apache.avro.generic.GenericRecord (java.util.HashMap is in module java.base of loader 'bootstrap'; org.apache.avro.generic.GenericRecord is in unnamed module of loader 'app')
	at com.sksamuel.avro4s.AvroDataOutputStream.$anonfun$x$1$2(AvroDataOutputStream.scala:36)
	at com.sksamuel.avro4s.AvroDataOutputStream.$anonfun$x$1$2$adapted(AvroDataOutputStream.scala:35)
	at com.sksamuel.avro4s.AvroDataOutputStream.write(AvroDataOutputStream.scala:47)
	at avro.test.Avro4sMap$.$anonfun$mapToByteArray$1(Avro4sMap.scala:17)
	at avro.test.Avro4sMap$.main(Avro4sMap.scala:26)
	at avro.test.Avro4sMap.main(Avro4sMap.scala)
```

**Comment by andreas-schroeder** [comment]
The `AvroOutputStream` classes are intended to be used with case classes only (and input streams too); If you want to encode/decode primitive types (also, maps and arrays), you'd need to write your own.

**Comment by mtekp** [comment]
That explains it. Thanks a lot
