### ISSUE TITLE
Index out of bounds when deserializing binary data

### ISSUE THREAD

**Issue by kh-evgeniy** [sksamuel/avro4s#567]
Hi, I've encountered weird problem when trying to deserializing binary message. 
```
Index -2 out of bounds for length 2
java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.apache.avro.generic.GenericDatumReader.readEnum(GenericDatumReader.java:267)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:181)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:259)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:247)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:187)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:259)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:247)
	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$1.next(AvroBinaryInputStream.scala:28)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$1.next(AvroBinaryInputStream.scala:26)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$2.next(AvroBinaryInputStream.scala:36)
	at scala.collection.Iterator.toStream(Iterator.scala:1418)
	at scala.collection.Iterator.toStream$(Iterator.scala:1417)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$2.toStream(AvroBinaryInputStream.scala:34)
	at scala.collection.TraversableOnce.toSeq(TraversableOnce.scala:298)
	at scala.collection.TraversableOnce.toSeq$(TraversableOnce.scala:298)
	at com.sksamuel.avro4s.AvroBinaryInputStream$$anon$2.toSeq(AvroBinaryInputStream.scala:34)
```

My code is straight forward:
```
    val file = new File("./kafka_avro_record")

    val array = new FileInputStream(file).readAllBytes()

    val in = AvroInputStream
      .binary[ManagementAction]
      .from(array)
      .build(AvroSchema.schema)

    val head = in.iterator.toSeq.head
    println(head)
```

**Comment by kh-evgeniy** [comment]
I found the problem, on the other side people used schema registry and therefore 5 bytes in the beginning of the message wasn't part of record. Is there a way to work with kafka though schema registry and avro4s?
