### ISSUE TITLE
ava.lang.ClassCastException: class com.sksamuel.avro4s.ImmutableRecord cannot be cast to class java.lang.CharSequence

### ISSUE THREAD

**Issue by Zhen-hao** [sksamuel/avro4s#574]
I use the following function in my Akka serializer:

```
  def toBin[T: Encoder](o: T): Array[Byte] = {

    val output = new ByteArrayOutputStream
    val avro = AvroOutputStream.binary[T].to(output).build()
    avro.write(o)
    avro.close()

    output.toByteArray
  }
```
but I got the following runtime exception

```
[info] Caused by: java.lang.ClassCastException: class com.sksamuel.avro4s.ImmutableRecord cannot be cast to class java.lang.CharSequence (com.sksamuel.avro4s.ImmutableRecord is in unnamed module of loader 'app'; java.lang.CharSequence is in module java.base of loader 'bootstrap')
[info]  at org.apache.avro.generic.GenericDatumWriter.writeString(GenericDatumWriter.java:323)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeString(GenericDatumWriter.java:315)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:150)
[info]  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:234)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:136)
[info]  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:206)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:195)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:130)
[info]  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:206)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:195)
[info]  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:130)
[info]  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
[info]  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:72)
[info]  at com.sksamuel.avro4s.DefaultAvroOutputStream.write(DefaultAvroOutputStream.scala:20)
```
on line `avro.write(o)`

**Comment by Zhen-hao** [comment]
the issue might be related to refined types. 

the type `Map[String Refined And[NonEmpty, MaxSize[300]], Option[String]]` got schema
```
"type" : {
          "type" : "array",
          "items" : "string"
        }
```
which looks very strange

**Comment by Zhen-hao** [comment]
found the real cause of the issue. 

I have my own type mapping for `Map` as 
```
/** ------------  scala.collection.immutable.Map ------------ */
  implicit def mapSchemaFor[K: SchemaFor, V: SchemaFor]: SchemaFor[scala.collection.immutable.Map[K, V]] =
    SchemaFor[scala.collection.immutable.Map[K, V]](AvroSchema[Vector[(K, V)]])

  implicit def mapEncoder[K: SchemaFor: Encoder, V: SchemaFor: Encoder]: Encoder[scala.collection.immutable.Map[K, V]] =
    new Encoder[scala.collection.immutable.Map[K, V]] {
      override val schemaFor = mapSchemaFor[K, V]
      override def encode(map: scala.collection.immutable.Map[K, V]) =
        Encoder[Vector[(K, V)]].encode(map.toVector)
    }

  implicit def mapDecoder[K: SchemaFor: Decoder, V: SchemaFor: Decoder]: Decoder[scala.collection.immutable.Map[K, V]] =
    new Decoder[scala.collection.immutable.Map[K, V]] {
      override val schemaFor = mapSchemaFor[K, V]
      override def decode(value: Any) =
        Map.from(Decoder[Vector[(K, V)]].decode(value))
    }
```
say in object `MyTypeMapping`.
if I run `AvroSchema[Map[String, Int]]`, it will get the correct result
```
Map schema is {"type":"array","items":{"type":"record","name":"Tuple2","namespace":"scala","fields":[{"name":"_1","type":"string"},{"name":"_2","type":"int"}]}}
```

But I if I run the same in a mother file with `import MyTypeMapping._` I got the wrong schema 
```
{"type":"array","items":"string"}
```
what's happening here?

**Comment by Zhen-hao** [comment]
to see the problems, run
```
  println(s"immutable Map schema is ${AvroSchema[Map[String, Int]]}")
  println(s"mutable Map schema is ${AvroSchema[scala.collection.mutable.Map[String, Int]]}")
```

**Comment by Zhen-hao** [comment]
found the real issue in https://github.com/sksamuel/avro4s/issues/577
