### ISSUE TITLE
Using Generic Type Serialisation

### ISSUE THREAD

**Issue by rabzu** [sksamuel/avro4s#61]
Hi,

Im trying to write a Generic serialization method for Avro4s :

```
  def toBinary[T](event: T)(implicit schemaFor: SchemaFor[T],  toRecord: ToRecord[T]) = {
    val baos = new ByteArrayOutputStream()
    val output = AvroOutputStream.binary[T](baos)
    output.write(event)
    output.close()
    baos.toByteArray
  }
```
But I get the following error:

` could not find implicit value for evidence parameter of type com.sksamuel.avro4s.ToRecord[T]`

I also try this:

```
def toBinary[T](event: T)(implicit schema: AvroSchema[T],  toRecord: ToRecord[T]) = {
    val baos = new ByteArrayOutputStream()
    val output = AvroOutputStream.binary[T](baos)
    output.write(event)
    output.close()
    baos.toByteArray
  }
```
and I get the following error:

```
org.apache.avro.reflect.AvroSchema does not take type parameters
[error]   def toBinary[T](event: T)(implicit schema: AvroSchema[T],  toRecord: ToRecord[T]) = {
```

Is there anyway I can generalise the serialisation?

**Comment by sksamuel** [comment]
What are you trying to serialize. Is it a case class?

**Comment by rabzu** [comment]
Yes case classes

Kind regards
Zuka




On Mon, Aug 29, 2016 at 1:16 PM +0100, "Stephen Samuel" <notifications@github.com> wrote:












What are you trying to serialize. Is it a case class?

**Comment by sksamuel** [comment]
This works for me with avro4s 1.6.0 and scala 2.11.8

```scala
case class Foo(str: String)
object Test extends App {

  val foo = Foo("hello")
  println(toBinary(foo))

  def toBinary[T: SchemaFor : ToRecord](event: T): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val output = AvroOutputStream.binary[T](baos)
    output.write(event)
    output.close()
    baos.toByteArray
  }
}
```

**Comment by rabzu** [comment]
Thank you, your solution worked. Now Im trying to Deserialize it using the following code but I get new errors:

```
case class Foo(str: String)

  val foo = Foo("hello")
  val b = toBinary(foo)
  val p = fromBinary(b)

  println(b)
  println(p)

  def toBinary[T: SchemaFor : ToRecord](event: T): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val output = AvroOutputStream.binary[T](baos)
    output.write(event)
    output.close()
    baos.toByteArray
  }


def fromBinary[T: SchemaFor : ToRecord](bytes: Array[Byte])= {
  val in = new ByteArrayInputStream(bytes)
  val input = AvroInputStream.binary[T](in)
  input.iterator.toSeq
}
```

Errors:

```
Error:(27, 41) could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[T]
  val input = AvroInputStream.binary[T](in)

Error:(27, 41) not enough arguments for method binary: (implicit evidence$11: com.sksamuel.avro4s.SchemaFor[T], implicit evidence$12: com.sksamuel.avro4s.FromRecord[T])com.sksamuel.avro4s.AvroBinaryInputStream[T].
Unspecified value parameter evidence$12.
  val input = AvroInputStream.binary[T](in)
                                       ^

Error:(11, 25) ambiguous implicit values:
 both object LongSchemaFor in object SchemaFor of type com.sksamuel.avro4s.SchemaFor.LongSchemaFor.type
 and object IntSchemaFor in object SchemaFor of type com.sksamuel.avro4s.SchemaFor.IntSchemaFor.type
 match expected type com.sksamuel.avro4s.SchemaFor[T]
lazy val p = fromBinary(b)
                       ^
```

**Comment by sksamuel** [comment]
You need `FromRecord` for deserialization.

**Comment by rabzu** [comment]
I appologise, I have another Macro expansion error. Maybe there is something I dont understand:


```
   def fromBinary[T: SchemaFor : ToRecord](bytes: Array[Byte]) = {
       val fromRecord = FromRecord.apply[T]
       val in = new ByteArrayInputStream(bytes)
       val input = AvroInputStream.binary[T](in)
       input.close()
       input.iterator.toSeq
   }

```
Error:
```
 exception during macro expansion: 
[error] scala.ScalaReflectionException: type T is not a class
[error]         at scala.reflect.api.Symbols$SymbolApi$class.asClass(Symbols.scala:275)
[error]         at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:84)
[error]         at com.sksamuel.avro4s.FromRecord$.applyImpl(FromRecord.scala:226)
[error]     val fromRecord = FromRecord.apply[T]
[error]                                      ^
 could not find implicit value for evidence parameter of type com.sksamuel.avro4s.FromRecord[T]
[error]       val input = AvroInputStream.binary[T](in)
[error]   
```                                         ^

**Comment by rabzu** [comment]
ofcourse  thanks

**Comment by rrodseth** [comment]
I have the following
```
object AvroSerializer {
  def toBinary[T: SchemaFor : ToRecord](data: T): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val output = AvroOutputStream.binary[T](baos)
    output.write(data)
    output.close()
    val result = baos.toByteArray
    result
  }

  def fromBinary[T >: Null : SchemaFor : FromRecord](data: Array[Byte]): T = {

    val input = AvroInputStream.binary[T](data)
    val result: T = if (input.iterator.isEmpty) {
      null 
    } else {
      input.iterator.toSeq.head
    }
    result
  }
```
I can use it in an Akka serializer like this
```
  override def toBinary(obj: AnyRef): Array[Byte] = {
    obj match {
      // Why doesn't AvroSerializer.toBinary(obj) work? It compiles, but writes an empty array
      case a: Foo => AvroSerializer.toBinary[Foo](a)
      case b: Bar => AvroSerializer.toBinary[Bar](b)
    }
  }
```
but as noted in the comment, an empty byte array gets written to the event store if I just do `AvroSerializer.toBinary(obj)`.

Adding this here in case you can explain this to me, or in case it saves someone else some debugging time.
Thanks.

**Comment by sksamuel** [comment]
You don't know the type at compile time in your commented out row.

**Comment by rrodseth** [comment]
But apparently the implicits still resolve, because I don't get compile errors.

**Comment by sksamuel** [comment]
It's just making an AvroSchema for AnyRef, which has no fields, so its an empty array.

**Comment by rrodseth** [comment]
I see. Thanks.
