### ISSUE TITLE
Encoder fails when custom value class used as default values

### ISSUE THREAD

**Issue by silles79** [sksamuel/avro4s#664]
using 4.0.9

```
import com.sksamuel.avro4s.Encoder

case class Name(price:String) extends AnyVal
case class Bar(price: Name = Name("foo"))

object Avro4sBug extends App {
    Encoder[Bar].encode(Bar(Name("ho")))
}
```

blows up with
```
Exception in thread "main" org.apache.avro.AvroRuntimeException: Not a record: "string"
	at org.apache.avro.Schema.getField(Schema.java:271)
	at com.sksamuel.avro4s.CustomDefaults$.$anonfun$customDefault$2(CustomDefaults.scala:39)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.immutable.MapBuilderImpl.addAll(Map.scala:692)
	at scala.collection.immutable.Map$.from(Map.scala:643)
	at scala.collection.immutable.Map$.from(Map.scala:173)
	at scala.collection.MapOps.map(Map.scala:299)
	at scala.collection.MapOps.map$(Map.scala:299)
	at scala.collection.AbstractMap.map(Map.scala:405)
	at com.sksamuel.avro4s.CustomDefaults$.customDefault(CustomDefaults.scala:33)
	at com.sksamuel.avro4s.DefaultResolver$.apply(DefaultResolver.scala:47)
	at com.sksamuel.avro4s.Records$.buildSchemaField(Records.scala:204)
	at com.sksamuel.avro4s.RecordFields$.com$sksamuel$avro4s$RecordFields$$buildField(RecordFields.scala:153)
	at com.sksamuel.avro4s.RecordFields$FieldEncoder.apply(RecordFields.scala:44)
	at com.sksamuel.avro4s.Records$.$anonfun$encoder$1(Records.scala:94)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at com.sksamuel.avro4s.Records$.encoder(Records.scala:92)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.$anonfun$encoder$2(MagnoliaDerived.scala:58)
	at scala.Option.getOrElse(Option.scala:201)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.encoder(MagnoliaDerived.scala:57)
	at com.sksamuel.avro4s.ResolvableEncoder.adhocInstance(Encoder.scala:91)
	at com.sksamuel.avro4s.ResolvableEncoder.adhocInstance$(Encoder.scala:91)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.adhocInstance$lzycompute(MagnoliaDerived.scala:54)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.adhocInstance(MagnoliaDerived.scala:54)
	at com.sksamuel.avro4s.ResolvableEncoder.encode(Encoder.scala:93)
	at com.sksamuel.avro4s.ResolvableEncoder.encode$(Encoder.scala:93)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.encode(MagnoliaDerived.scala:54)
	at Avro4sBug$.delayedEndpoint$Avro4sBug$1(Avro4sBug.scala:8)
	at Avro4sBug$delayedInit$body.apply(Avro4sBug.scala:6)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Avro4sBug$.main(Avro4sBug.scala:6)
	at Avro4sBug.main(Avro4sBug.scala)

```

works fine when AnyVal is removed

**Comment by guizmaii** [comment]
Same problem with `refined`:

```scala
case class Foo(nonEmptyStr: NonEmptyString = "toto")
```

Generate this error at compile time:

```scala
[info] - should accept default value *** FAILED ***
[info]   org.apache.avro.AvroRuntimeException: Unknown datum class: class eu.timepit.refined.api.Refined
[info]   at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
[info]   at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
[info]   at org.apache.avro.Schema$Field.<init>(Schema.java:558)
[info]   at com.sksamuel.avro4s.Records$.buildSchemaField(Records.scala:242)
[info]   at com.sksamuel.avro4s.Records$.$anonfun$schema$1(Records.scala:149)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
[info]   at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
[info]   at com.sksamuel.avro4s.Records$.schema(Records.scala:143)
[info]   at com.sksamuel.avro4s.MagnoliaDerivedSchemaFors$$anon$2.$anonfun$schemaFor$2(MagnoliaDerived.scala:30)
```

**Comment by guizmaii** [comment]
This issue is fixed.
