### ISSUE TITLE
Unable to derive AvroSchema for field with list of enum as default value

### ISSUE THREAD

**Issue by KirilYurovnikRiski** [sksamuel/avro4s#677]
The following code:
```scala
package test

import com.sksamuel.avro4s._

sealed trait Color
case object Red extends Color
case object Green extends Color

case class Foo(colors: List[Color] = List(Red))

object Main {
  def main(args: Array[String]): Unit = {
    println(AvroSchema[Foo])
  }
}
```
fails with the following error:
```
Exception in thread "main" org.apache.avro.AvroRuntimeException: Unknown datum class: class test.Red$
	at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:96)
	at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:74)
	at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:53)
	at org.apache.avro.Schema$Field.<init>(Schema.java:586)
	at com.sksamuel.avro4s.Records$.buildSchemaField(Records.scala:242)
	at com.sksamuel.avro4s.Records$.$anonfun$schema$1(Records.scala:149)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.sksamuel.avro4s.Records$.schema(Records.scala:143)
	at com.sksamuel.avro4s.MagnoliaDerivedSchemaFors$$anon$2.$anonfun$schemaFor$2(MagnoliaDerived.scala:30)
	at scala.Option.getOrElse(Option.scala:189)
	at com.sksamuel.avro4s.MagnoliaDerivedSchemaFors$$anon$2.schemaFor(MagnoliaDerived.scala:29)
	at com.sksamuel.avro4s.SchemaFor.resolveSchemaFor(SchemaFor.scala:53)
	at com.sksamuel.avro4s.SchemaFor.resolveSchemaFor$(SchemaFor.scala:51)
	at com.sksamuel.avro4s.MagnoliaDerivedSchemaFors$$anon$2.resolveSchemaFor(MagnoliaDerived.scala:26)
	at com.sksamuel.avro4s.SchemaFor.resolveSchemaFor(SchemaFor.scala:40)
	at com.sksamuel.avro4s.SchemaFor.resolveSchemaFor$(SchemaFor.scala:40)
	at com.sksamuel.avro4s.MagnoliaDerivedSchemaFors$$anon$2.resolveSchemaFor(MagnoliaDerived.scala:26)
	at com.sksamuel.avro4s.AvroSchema$.apply(AvroSchema.scala:20)
```

Expected result:
```json
{"type":"record","name":"Foo","namespace":"test","fields":[{"name":"colors","type":{"type":"array","items":{"type":"enum","name":"Color","symbols":["Green","Red"]}},"default":["Red"]}]}
```

While it works as expected if you change `Foo` to:
```scala
case class Foo(color: Color = Red)
```
which yields:
```json
{"type":"record","name":"Foo","namespace":"test","fields":[{"name":"color","type":{"type":"enum","name":"Color","symbols":["Green","Red"]},"default":"Red"}]}
```

Tested on v4.0.10 for 2.12 and 2.13 - same thing happens in both.

**Comment by sksamuel** [comment]
4.0.11 released
