### ISSUE TITLE
java.lang.InternalError: Malformed class name when using a default enum value

### ISSUE THREAD

**Issue by RoccoMathijn** [sksamuel/avro4s#684]
Hey, this small example with a default enum value fails with `java.lang.InternalError: Malformed class name`

Not sure if i'm doing something wrong or if it's a bug. 
```scala
import com.sksamuel.avro4s.RecordFormat

object MalformedClassNameExample extends App {
  sealed trait Colour
  object Colours {
    case object Red  extends Colour
    case object Blue extends Colour
  }
  
  case class Record(colour: Colour = Colours.Red)
  
  val formatter = RecordFormat[Record]

  val record = Record(Colours.Blue)

  formatter.to(record)
}
```
```
Exception in thread "main" java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at com.sksamuel.avro4s.CustomDefaults$.trimmedClassName(CustomDefaults.scala:84)
	at com.sksamuel.avro4s.CustomDefaults$.customDefault(CustomDefaults.scala:28)
	at com.sksamuel.avro4s.DefaultResolver$.apply(DefaultResolver.scala:54)
	at com.sksamuel.avro4s.Records$.buildSchemaField(Records.scala:204)
	at com.sksamuel.avro4s.RecordFields$.com$sksamuel$avro4s$RecordFields$$buildField(RecordFields.scala:153)
	at com.sksamuel.avro4s.RecordFields$FieldEncoder.apply(RecordFields.scala:44)
	at com.sksamuel.avro4s.Records$.$anonfun$encoder$1(Records.scala:94)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at com.sksamuel.avro4s.Records$.encoder(Records.scala:92)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.$anonfun$encoder$2(MagnoliaDerived.scala:58)
	at scala.Option.getOrElse(Option.scala:201)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.encoder(MagnoliaDerived.scala:57)
	at com.sksamuel.avro4s.ResolvableEncoder.adhocInstance(Encoder.scala:91)
	at com.sksamuel.avro4s.ResolvableEncoder.adhocInstance$(Encoder.scala:91)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.adhocInstance$lzycompute(MagnoliaDerived.scala:54)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.adhocInstance(MagnoliaDerived.scala:54)
	at com.sksamuel.avro4s.ResolvableEncoder.encode(Encoder.scala:93)
	at com.sksamuel.avro4s.ResolvableEncoder.encode$(Encoder.scala:93)
	at com.sksamuel.avro4s.MagnoliaDerivedEncoders$$anon$4.encode(MagnoliaDerived.scala:54)
	at com.sksamuel.avro4s.ToRecord$$anon$1.to(ToRecord.scala:22)
	at com.sksamuel.avro4s.RecordFormat$$anon$1.to(RecordFormat.scala:21)
	at example.MalformedClassNameExample$.delayedEndpoint$example$MalformedClassNameExample$1(MalformedClassNameExample.scala:18)
	at example.MalformedClassNameExample$delayedInit$body.apply(MalformedClassNameExample.scala:5)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at example.MalformedClassNameExample$.main(MalformedClassNameExample.scala:5)
	at example.MalformedClassNameExample.main(MalformedClassNameExample.scala)
```

**Comment by RoccoMathijn** [comment]
I found out that if I move the ADT out of the MalformedClassNameExample object to top level there is no problem.

I'll just do that. Thanks

Leaving the decision to close the issue to the maintainers ;)

**Comment by sksamuel** [comment]
A `java.lang.InternalError` is probably an issue with the way the scala compiler chooses a name for the inner class. The exception is throw when calling `p.getClass.getSimpleName` and that should never fail in libraries, so I think this isn't an avro4s problem.
