### ISSUE TITLE
UnresolvedUnionException: Not in union error 

### ISSUE THREAD

**Issue by btanyab** [sksamuel/avro4s#689]
Hi, we are seeing the UnresolvedUnionException when overriding the name space of an optional either. 
Here is our reproducible example:
```scala
final case class Ingredients(one: String, two: Option[String] = None)

final case class Cheese(@AvroNamespace("pizza.favourite.namespace") ingredients: Option[Ingredients] = None)
final case class Salami(@AvroNamespace("pizza.favourite.namespace") ingredients: Option[Ingredients] = None)

final case class Pepperoni(salami: Salami, cheese: Cheese)
final case class Margarita(cheese: Cheese)

final case class Pizza(
    @AvroNamespace("pizza.namespace")
    favourite: Option[Either[Pepperoni, Margarita]] = None
)
```

So when we are encoding the GenericRecord we get this error:

<details>
<summary>stacktrace</summary>

```
org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"record","name":"Pepperoni","namespace":"pizza.namespace","fields":[{"name":"salami","type":{"type":"record","name":"Salami","fields":[{"name":"ingredients","type":["null",{"type":"record","name":"Ingredients","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}],"default":null}]}},{"name":"cheese","type":{"type":"record","name":"Cheese","fields":[{"name":"ingredients","type":["null","Ingredients"],"default":null}]}}]},{"type":"record","name":"Margarita","namespace":"pizza.namespace","fields":[{"name":"cheese","type":"Cheese"}]}]: ImmutableRecord({"type":"record","name":"Margarita","namespace":"pizza.namespace","fields":[{"name":"cheese","type":{"type":"record","name":"Cheese","namespace":"line9.read.iw.iw.iw.iw.iw.iw","fields":[{"name":"ingredients","type":["null",{"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}],"default":null}]}}]},WrappedArray(ImmutableRecord({"type":"record","name":"Cheese","namespace":"line9.read.iw.iw.iw.iw.iw.iw","fields":[{"name":"ingredients","type":["null",{"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}],"default":null}]},WrappedArray(ImmutableRecord({"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]},WrappedArray(cheddar, ham)))))) (field=favourite)
  at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:223)
  at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
  at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
  at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
  at .toBytes(<console>:25)
  ... 37 elided
  Suppressed: org.apache.avro.UnresolvedUnionException: Not in union {"type":"record","name":"Cheese","namespace":"pizza.namespace","fields":[{"name":"ingredients","type":["null",{"type":"record","name":"Ingredients","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}],"default":null}]}: ImmutableRecord({"type":"record","name":"Cheese","namespace":"line9.read.iw.iw.iw.iw.iw.iw","fields":[{"name":"ingredients","type":["null",{"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}],"default":null}]},WrappedArray(ImmutableRecord({"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]},WrappedArray(cheddar, ham)))) (field=cheese)
    at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:223)
    at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
    at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
    at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
    at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145)
    at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
    at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221)
    ... 42 more
    Suppressed: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"record","name":"Ingredients","namespace":"pizza.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}]: ImmutableRecord({"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]},WrappedArray(cheddar, ham)) (field=ingredients)
      at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:223)
      at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
      at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
      at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
      at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221)
      at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
      at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
      at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
      at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145)
      at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
      at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221)
      at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
      at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
      at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
      at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
      at .toBytes(<console>:25)
      Suppressed: org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"record","name":"Ingredients","namespace":"pizza.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]}]: ImmutableRecord({"type":"record","name":"Ingredients","namespace":"pizza.favourite.namespace","fields":[{"name":"one","type":"string"},{"name":"two","type":["null","string"],"default":null}]},WrappedArray(cheddar, ham))
        at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:896)
        at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:272)
        at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:143)
        at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
        at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221)

```
</details>

However, if we change an `Option` to a `Set` in `ingredients: Set[Ingredients]`, then it work as intended.

Any help to resolve this would be appreciated. Thanks

P.S the namespace `@AvroNamespace("pizza.namespace")` is a requirement for our use case.

**Comment by btanyab** [comment]
We believe that the problem could be related to the namespace inconsistencies between the schema and the ImmutableRecord. In the schema the name space is `pizza.namespace` as expected, however in the ImmutableRecord `Cheese` gets `"namespace":"line9.read.iw.iw.iw.iw.iw.iw"`

**Comment by sksamuel** [comment]
Which versions ?

**Comment by btanyab** [comment]
>Which versions ?

We are using Scala 2 and avro4s v4.0.11.

**Comment by sksamuel** [comment]
Do you have a full example, specifically where you write out the record and see the exception raised.

**Comment by btanyab** [comment]
If you run this in a scala worksheet you should see the error.
```scala

import com.sksamuel.avro4s.AvroNamespace
import com.sksamuel.avro4s._
import org.apache.avro.generic._
import org.apache.avro.io.EncoderFactory

import java.io.ByteArrayOutputStream

final case class Ingredients(one: String, two: Option[String] = None)

final case class Cheese(@AvroNamespace("pizza.favorite.namespace") ingredients: Option[Ingredients] = None)
final case class Salami(@AvroNamespace("pizza.favorite.namespace") ingredients: Option[Ingredients] = None)

final case class Pepperoni(salami: Salami, cheese: Cheese)
final case class Margarita(cheese: Cheese)
final case class Pizza(
    @AvroNamespace("pizza.namespace")
    favorite: Option[Either[Pepperoni, Margarita]] = None
)

def entityToRecord(pz: Pizza): GenericRecord = ToRecord[Pizza].to(pz)

val pizza = Pizza(Some(Right(Margarita(Cheese(Some(Ingredients("cheddar", Some("ham"))))))))

val schema = AvroSchema[Pizza]

def toBytes(record: GenericRecord): Array[Byte] = {
  val writer  = new GenericDatumWriter[GenericRecord](schema)
  val out     = new ByteArrayOutputStream()
  val encoder = EncoderFactory.get().binaryEncoder(out, null)
  writer.write(record, encoder)
  encoder.flush() 
  out.toByteArray
}

toBytes(entityToRecord(pizza))

/*
 * Works when:
 * final case class Cheese(@AvroNamespace("pizza.favorite.namespace") ingredients: Set[Ingredients])
 * final case class Salami(@AvroNamespace("pizza.favorite.namespace") ingredients: Set[Ingredients])
 *
 * val pizza = Pizza(Some(Right(Margarita(Cheese(Set(Ingredients("cheddar", Some("ham"))))))))
 *
 * */

```

**Comment by sksamuel** [comment]
Looks like the namespace override doesn't work for options.

**Comment by sksamuel** [comment]
Never mind its not that.

**Comment by sksamuel** [comment]
Yeah actually I think it is, if I change cheese to this:

final case class Cheese(@AvroNamespace("qweqeqwe") ingredients: Option[Ingredients] = None)

Then qweqeqwe doesn't show up in the schema output. But it's not as simple as just namespaces on options, as that I added a test for and does work. So it might be related to the either around it as well.

**Comment by sksamuel** [comment]
The issue is that @AvroNamespace is applied down the tree. If you apply it to a field to override the namespace then all nested types need to use the same namespace, or avro will default to no namespace. 

But when you have nested annotations it's overriding the namespace that was set earlier (since the inner types are generated first). I can't see an easy way of having avro4s determine when to "stop" applying the namespaces without breaking a lot of existing expectations.

**Comment by btanyab** [comment]
Thanks for trying to resolve the issue. Eventually, we had to duplicate `Pepperoni` and `Margarita` and place them in a separate package in order to get rid of the annotation `@AvroNamespace("pizza.namespace")`. 
I guess the issue can be closed now.
