### ISSUE TITLE
java.lang.ClassNotFoundException when decoding Scala enums

### ISSUE THREAD

**Issue by ivanoronee** [sksamuel/avro4s#712]
When running in an environment that uses multiple classloaders, Scala enum classes are occasionally not found. 

From poking around the code I believe this is caused by the call  below in `com.sksamuel.avro4s.BaseDecoders.ScalaEnumDecoder`
```
val mirror: Mirror = runtimeMirror(getClass.getClassLoader)
```

A similar issue existed in Kafka and was fixed https://issues.apache.org/jira/browse/KAFKA-3218 

Below is the stack trace from the exception.
```
java.lang.ClassNotFoundException: com.mycompany.ScalaEnumObject$
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at scala.reflect.runtime.ReflectionUtils$.staticSingletonInstance(ReflectionUtils.scala:70)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaModuleMirror.instance(JavaMirrors.scala:584)
	at com.sksamuel.avro4s.BaseDecoders$ScalaEnumDecoder.<init>(BaseTypes.scala:388)
	at com.sksamuel.avro4s.BaseDecoders.scalaEnumDecoder(BaseTypes.scala:376)
	at com.sksamuel.avro4s.BaseDecoders.scalaEnumDecoder$(BaseTypes.scala:376)
	at com.sksamuel.avro4s.Decoder$.scalaEnumDecoder(Decoder.scala:102)
```

Library version being used: `4.0.12`
Java version: 11.0.11
Scala version: 2.13.8

**Comment by ivanoronee** [comment]
Fixed in https://github.com/sksamuel/avro4s/pull/713
