### ISSUE TITLE
StackOverflow when generating schema of complex nested object

### ISSUE THREAD

**Issue by blair-anson** [sksamuel/avro4s#97]
I've defined the following simple scala program to generate an Avro schema using your library.
It works fine for the Pizza example, but when I attempt to use it for a complex nested class it fails with the following error....
```
Exception in thread "main" java.lang.StackOverflowError
	at org.apache.avro.Schema.validateDefault(Schema.java:1165)
	at org.apache.avro.Schema.access$300(Schema.java:81)
	at org.apache.avro.Schema$Field.<init>(Schema.java:406)
	at org.apache.avro.Schema$Field.<init>(Schema.java:423)
	at org.apache.avro.Schema$Field.<init>(Schema.java:415)
	at com.sksamuel.avro4s.SchemaFor$.fieldBuilder(SchemaFor.scala:424)
	at com.sksamuel.avro4s.SchemaFor$.fieldBuilder(SchemaFor.scala:406)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60$$anonfun$40.apply(App.scala:16)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60$$anonfun$40.apply(App.scala:16)
	at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
	at shapeless.Lazy$$anon$1.value(lazy.scala:121)
	at shapeless.Lazy$$anonfun$map$1.apply(lazy.scala:114)
	at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
	at shapeless.Lazy$$anon$1.value(lazy.scala:121)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60.apply(App.scala:16)
	at com.sksamuel.avro4s.LowPriorityToSchema$$anon$1.<init>(SchemaFor.scala:22)
	at com.sksamuel.avro4s.LowPriorityToSchema$class.apply(SchemaFor.scala:21)
	at com.sksamuel.avro4s.ToSchema$.apply(SchemaFor.scala:28)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1.inst$macro$30$lzycompute(App.scala:16)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1.inst$macro$30(App.scala:16)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60$$anonfun$40$$anonfun$apply$214.apply(App.scala:16)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60$$anonfun$40$$anonfun$apply$214.apply(App.scala:16)
	at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
	at shapeless.Lazy$$anon$1.value(lazy.scala:121)
	at com.sksamuel.avro4s.SchemaFor$.fieldBuilder(SchemaFor.scala:406)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60$$anonfun$40.apply(App.scala:16)
	at com.example.App$$anon$1$$anonfun$1$anon$apply$macro$80$1$$anon$60$$anonfun$40.apply(App.scala:16)
	at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)

<<...SNIP...>>
The same error repeats 
```

I suspect it might be due to the Object having a nested self reference.

My code is as follows....
```
package com.example
import com.sksamuel.avro4s.AvroSchema

object App {
   
  def main(args : Array[String]) {
    val schema = AvroSchema[gnipTweet]
    println(schema)
  }
}

case class Links(
                  href: String,
                  rel: String
                )
case class Location(
                     objectType: String,
                     displayName: String
                   )
case class Actor(
                  objectType: String,
                  id: String,
                  link: String,
                  displayName: String,
                  postedTime: String,
                  image: String,
                  summary: String,
                  links: List[Links],
                  friendsCount: Double,
                  followersCount: Double,
                  listedCount: Double,
                  statusesCount: Double,
                  twitterTimeZone: String,
                  verified: Boolean,
                  utcOffset: String,
                  preferredUsername: String,
                  languages: List[String],
                  location: Location,
                  favoritesCount: Double
                )
case class Generator(
                      displayName: String,
                      link: String
                    )
case class Provider(
                     objectType: String,
                     displayName: String,
                     link: String
                   )
case class ObjectBis(
                      id: String,
                      summary: String,
                      objectType: String,
                      actor: Actor,
                      verb: String,
                      postedTime: String,
                      generator: Generator,
                      provider: Provider,
                      link: String,
                      body: String,
                      `object`: ObjectBis,
                      favoritesCount: Double,
                      twitter_entities: Twitter_entities,
                      twitter_filter_level: String,
                      twitter_lang: String,
                      display_text_range: List[Double],
                      long_object: Long_object
                            )
case class Long_object(
                        body: String,
                        display_text_range: List[Double],
                        twitter_entities: Twitter_entities,
                        twitter_extended_entities: Twitter_extended_entities
                      )
case class Hashtags(
                     text: String,
                     indices: List[Double]
                   )
case class User_mentions(
                          screen_name: String,
                          name: String,
                          id: Double,
                          id_str: String,
                          indices: List[Double]
                        )
case class Medium(
                   w: Double,
                   h: Double,
                   resize: String
                 )
case class Sizes(
                  medium: Medium,
                  small: Medium,
                  large: Medium,
                  thumb: Medium
                )
case class Media(
                  id: Double,
                  id_str: String,
                  indices: List[Double],
                  media_url: String,
                  media_url_https: String,
                  url: String,
                  display_url: String,
                  expanded_url: String,
                  `type`: String,
                  sizes: Sizes
                )
case class Urls(
                 url: String,
                 expanded_url: String,
                 display_url: String,
                 indices: List[Double],
                 expanded_status: Double,
                 expanded_url_title: String,
                 expanded_url_description: String
               )
case class Twitter_entities(
                             hashtags: List[Hashtags],
                             user_mentions: List[User_mentions],
                             symbols: List[Hashtags],
                             media: List[Media],
                             urls: List[Urls]
                           )
case class Twitter_extended_entities(
                                      media: List[Media]
                                    )
case class Matching_rules(
                           tag: String,
                           id: Double
                         )
case class Geo(
                coordinates: List[Double],
                `type`: String
              )
case class Address(
                    country: String,
                    countryCode: String,
                    region: String
                  )
case class ProfileLocations(
                             objectType: String,
                             geo: Geo,
                             address: Address,
                             displayName: String
                           )
case class Gnip(
                 matching_rules: List[Matching_rules],
                 urls: List[Urls],
                 profileLocations: List[ProfileLocations]
               )
case class gnipTweet(
                           id: String,
                           objectType: String,
                           actor: Actor,
                           verb: String,
                           postedTime: String,
                           generator: Generator,
                           provider: Provider,
                           link: String,
                           body: String,
                           `object`: ObjectBis,
                           favoritesCount: Double,
                           twitter_entities: Twitter_entities,
                           twitter_extended_entities: Twitter_extended_entities,
                           twitter_filter_level: String,
                           twitter_lang: String,
                           display_text_range: List[Double],
                           retweetCount: Double,
                           gnip: Gnip
                         )

````

**Comment by sksamuel** [comment]
It won't support cyclic references, and the `Actor` instance is probably too complex.

**Comment by blair-anson** [comment]
Ah that would be it. Thanks, I'll manage the cyclic reference manually.
